# encode
BROTLI_MIN_WINDOW_BITS = 10
BROTLI_MAX_WINDOW_BITS = 24
BROTLI_LARGE_MAX_WINDOW_BITS = 30
BROTLI_MIN_INPUT_BLOCK_BITS = 16
BROTLI_MAX_INPUT_BLOCK_BITS = 24
BROTLI_MIN_QUALITY = 0
BROTLI_MAX_QUALITY = 11

BROTLI_DEFAULT_QUALITY = 11
BROTLI_DEFAULT_WINDOW = 22
BROTLI_DEFAULT_MODE = 0
