PyBUF_MAX_NDIM = 64

PyBUF_SIMPLE = 0
PyBUF_WRITABLE = 0x0001

PyBUF_FORMAT = 0x0004
PyBUF_ND = 0x0008
PyBUF_STRIDES = 0x0010 | PyBUF_ND
PyBUF_C_CONTIGUOUS = 0x0020 | PyBUF_STRIDES
PyBUF_F_CONTIGUOUS = 0x0040 | PyBUF_STRIDES
PyBUF_ANY_CONTIGUOUS = 0x0080 | PyBUF_STRIDES
PyBUF_INDIRECT = 0x0100 | PyBUF_STRIDES

PyBUF_CONTIG = PyBUF_ND | PyBUF_WRITABLE
PyBUF_CONTIG_RO = PyBUF_ND

PyBUF_STRIDED = PyBUF_STRIDES | PyBUF_WRITABLE
PyBUF_STRIDED_RO = PyBUF_STRIDES

PyBUF_RECORDS = PyBUF_STRIDES | PyBUF_WRITABLE | PyBUF_FORMAT
PyBUF_RECORDS_RO = PyBUF_STRIDES | PyBUF_FORMAT

PyBUF_FULL = PyBUF_INDIRECT | PyBUF_WRITABLE | PyBUF_FORMAT
PyBUF_FULL_RO = PyBUF_INDIRECT | PyBUF_FORMAT

PyBUF_READ = 0x100
PyBUF_WRITE = 0x200
