from . import INT_MAX as _INT_MAX
from . import is_32bits as _is_32bits

# zstd
ZSTD_VERSION_MAJOR = 1
ZSTD_VERSION_MINOR = 5
ZSTD_VERSION_RELEASE = 5
ZSTD_VERSION_NUMBER = ZSTD_VERSION_MAJOR * 100 * 100 + ZSTD_VERSION_MINOR * 100 + ZSTD_VERSION_RELEASE

ZSTD_CLEVEL_DEFAULT = 3

ZSTD_MAGICNUMBER = 0xFD2FB528
ZSTD_MAGIC_DICTIONARY = 0xEC30A437
ZSTD_MAGIC_SKIPPABLE_START = 0x184D2A50
ZSTD_MAGIC_SKIPPABLE_MASK = 0xFFFFFFF0

ZSTD_BLOCKSIZELOG_MAX = 17
ZSTD_BLOCKSIZE_MAX = 1 << ZSTD_BLOCKSIZELOG_MAX

ZSTD_FRAMEHEADERSIZE_MAX = 18
ZSTD_SKIPPABLEHEADERSIZE = 8

ZSTD_WINDOWLOG_MAX_32 = 30
ZSTD_WINDOWLOG_MAX_64 = 31
ZSTD_WINDOWLOG_MAX = ZSTD_WINDOWLOG_MAX_32 if _is_32bits else ZSTD_WINDOWLOG_MAX_64
ZSTD_WINDOWLOG_MIN = 10
ZSTD_HASHLOG_MAX = ZSTD_WINDOWLOG_MAX if ZSTD_WINDOWLOG_MAX < 30 else 30
ZSTD_HASHLOG_MIN = 6
ZSTD_CHAINLOG_MAX_32 = 29
ZSTD_CHAINLOG_MAX_64 = 30
ZSTD_CHAINLOG_MAX = ZSTD_CHAINLOG_MAX_32 if _is_32bits else ZSTD_CHAINLOG_MAX_64
ZSTD_CHAINLOG_MIN = ZSTD_HASHLOG_MIN
ZSTD_SEARCHLOG_MAX = (ZSTD_WINDOWLOG_MAX - 1)
ZSTD_SEARCHLOG_MIN = 1
ZSTD_MINMATCH_MAX = 7
ZSTD_MINMATCH_MIN = 3
ZSTD_TARGETLENGTH_MAX = ZSTD_BLOCKSIZE_MAX
ZSTD_TARGETLENGTH_MIN = 0
ZSTD_STRATEGY_MIN = 1
ZSTD_STRATEGY_MAX = 9
ZSTD_BLOCKSIZE_MAX_MIN = 1 << 10

ZSTD_OVERLAPLOG_MIN = 0
ZSTD_OVERLAPLOG_MAX = 9

ZSTD_WINDOWLOG_LIMIT_DEFAULT = 27

ZSTD_LDM_HASHLOG_MIN = ZSTD_HASHLOG_MIN
ZSTD_LDM_HASHLOG_MAX = ZSTD_HASHLOG_MAX
ZSTD_LDM_MINMATCH_MIN = 4
ZSTD_LDM_MINMATCH_MAX = 4096
ZSTD_LDM_BUCKETSIZELOG_MIN = 1
ZSTD_LDM_BUCKETSIZELOG_MAX = 8
ZSTD_LDM_HASHRATELOG_MIN = 0
ZSTD_LDM_HASHRATELOG_MAX = ZSTD_WINDOWLOG_MAX - ZSTD_HASHLOG_MIN

ZSTD_TARGETCBLOCKSIZE_MIN = 64
ZSTD_TARGETCBLOCKSIZE_MAX = ZSTD_BLOCKSIZE_MAX
ZSTD_SRCSIZEHINT_MIN = 0
ZSTD_SRCSIZEHINT_MAX = _INT_MAX
