_DIGITS = '0123456789'
DESCRIPTION = 'Python Wallpaper Changer!'
DISPLAY = 'Unknown Display'
DISPLAY_ALL = 'All Displays'
FIRST_TITLE = 'Hello from Wallpyper! 👋'
FIRST = '👀 See the system tray icon?\nDouble click to change wallpaper,\nRight click to open context menu.'

FAIL_CHANGE = 'Failed Changing Wallpaper'
FAIL_CHANGE_LOCK = 'Failed Changing Lock Screen'
FAIL_CLEAR = 'Failed Clearing Wallpaper Cache'
FAIL_COPY = 'Failed Copying Image to Clipboard'
FAIL_COPY_PATH = 'Failed Copying Image Path to Clipboard'
FAIL_COPY_URL = 'Failed Copying Image URL'
FAIL_DESKTOP = 'Failed Adding Desktop Shortcut'
FAIL_OPEN = 'Failed Opening Image with Default App'
FAIL_OPEN_BROWSER = 'Failed Opening Image URL in Browser'
FAIL_OPEN_EXPLORER = 'Failed Opening Image in Explorer'
FAIL_OPEN_WITH = 'Failed Opening Image with Another App'
FAIL_PIN = 'Failed Pinning to Taskbar'
FAIL_PIN_START = 'Failed Pinning to Start'
FAIL_QUIT = 'Waiting for Running Tasks to Finish'
FAIL_REMOVE_DESKTOP = 'Failed Removing Desktop Shortcut'
FAIL_REMOVE_START_MENU = 'Failed Removing Start Menu Shortcut'
FAIL_SAVE = 'Failed Saving Image'
FAIL_SAVE_DIR = 'Failed Changing Save Location'
FAIL_SEARCH = 'Failed Searching Similar Images'
FAIL_START_MENU = 'Failed Adding Start Menu Shortcut'
FAIL_UNPIN = 'Failed Unpinning from Taskbar'
FAIL_UNPIN_START = 'Failed Unpinning from Start'

LABEL_ABOUT = 'About Wallpyper'
LABEL_ANIMATE = 'Animate Tray Icon'
LABEL_AUTO_SAVE = 'Auto Save Wallpaper'
LABEL_BING = 'Bing Similar Images'
LABEL_CACHE = 'Keep Wallpaper Cache'
LABEL_CHANGE = 'Change Wallpaper'
LABEL_CLEAR = 'Clear Recent List'
LABEL_CLEAR_CACHE = 'Clear Wallpaper Cache'
LABEL_CONFIG = 'Save Wallpyper Settings'
LABEL_COPY = 'Copy Image'
LABEL_COPY_PATH = 'Copy Image Path'
LABEL_COPY_URL = 'Copy Image URL'
LABEL_DESKTOP = 'Add Desktop Shortcut'
LABEL_GOOGLE = 'Google Similar Images'
LABEL_NO_FADE = 'Disable Wallpaper Fading'
LABEL_NOTIFY = 'Show Error Notifications'
LABEL_OPEN = 'Open with Default App'
LABEL_OPEN_BROWSER = 'Open in Default Browser'
LABEL_OPEN_EXPLORER = 'Open in Explorer'
LABEL_OPEN_WITH = 'Open with...'
LABEL_PIN = 'Pin to Taskbar'
LABEL_PIN_START = 'Pin to Start'
LABEL_QUIT = 'Quit Wallpyper'
LABEL_REMOVE_DESKTOP = 'Remove Desktop Shortcut'
LABEL_REMOVE_START_MENU = 'Remove Start Menu Shortcut'
LABEL_RESET = 'Reset Wallpyper Settings'
LABEL_RESTART = 'Restart Wallpyper'
LABEL_SAVE = 'Save Image'
LABEL_SAVE_DIR = 'Change Save Location...'
LABEL_SEARCH = 'Reverse Image Search'
LABEL_SET = 'Set as Wallpaper'
LABEL_SET_LOCK = 'Set as Lock Screen'
LABEL_SKIP = 'Skip Recent Wallpapers'
LABEL_START = 'Start at User Sign-in'
LABEL_START_MENU = 'Add Start Menu Shortcut'
LABEL_UNPIN = 'Unpin from Taskbar'
LABEL_UNPIN_START = 'Unpin from Start'
LABEL_UPDATE_DISPLAY = 'Update Display List'

MENU_ACTIONS = 'Wallpyper Actions'
MENU_AUTO = 'Automate Wallpyper'
MENU_AUTO_CHANGE = 'Auto Change Wallpaper'
MENU_DISPLAY = 'Set Wallpaper for'
MENU_LINKS = 'Shortcuts && Pins'
MENU_MODULE = 'Wallpaper Provider'
MENU_RECENT = 'Recent Wallpapers'
MENU_SETTINGS = 'Wallpyper Settings'
MENU_STYLE = 'Wallpaper Fit Method'
MENU_TRANSITION = 'Transition Style'

STATUS_CHANGE = 'Changing Wallpaper'
STATUS_DOWNLOAD = 'Downloading Image'
STATUS_SEARCH = 'Uploading Image'

TIME_0 = 'Disabled'
TIME_300 = '5 Minute'
TIME_900 = '15 Minute'
TIME_1800 = '30 Minute'
TIME_3600 = '1 Hour'
TIME_10800 = '3 Hour'
TIME_21600 = '6 Hour'

STYLE_DEFAULT = 'Default'
STYLE_FILL = 'Fill'
STYLE_FIT = 'Fit'
STYLE_CENTER = 'Center'
STYLE_STRETCH = 'Stretch'
STYLE_TILE = 'Tile'
STYLE_SPAN = 'Span'

TRANSITION_DISABLED = 'Disabled'
TRANSITION_RANDOM = 'Random'
TRANSITION_FADE = 'Fade'
TRANSITION_EXPLODE = 'Explode'
TRANSITION_IMPLODE = 'Implode'
TRANSITION_LEFT = 'Left'
TRANSITION_TOP = 'Top'
TRANSITION_RIGHT = 'Right'
TRANSITION_BOTTOM = 'Bottom'
TRANSITION_TOP_LEFT = 'Top Left'
TRANSITION_TOP_RIGHT = 'Top Right'
TRANSITION_BOTTOM_LEFT = 'Bottom Left'
TRANSITION_BOTTOM_RIGHT = 'Bottom Right'
TRANSITION_VERTICAL = 'Vertical'
TRANSITION_HORIZONTAL = 'Horizontal'
TRANSITION_REVERSE_VERTICAL = 'Vertical'
TRANSITION_REVERSE_HORIZONTAL = 'Horizontal'
TRANSITION_SLIDE_LEFT = 'Slide Left'
TRANSITION_SLIDE_TOP = 'Slide Top'
TRANSITION_SLIDE_RIGHT = 'Slide Right'
TRANSITION_SLIDE_BOTTOM = 'Slide Bottom'
TRANSITION_SLIDE_TOP_LEFT = 'Slide Top Left'
TRANSITION_SLIDE_TOP_RIGHT = 'Slide Top Right'
TRANSITION_SLIDE_BOTTOM_LEFT = 'Slide Bottom Left'
TRANSITION_SLIDE_BOTTOM_RIGHT = 'Slide Bottom Right'
TRANSITION_SLIDE_VERTICAL = 'Slide Vertical'
TRANSITION_SLIDE_HORIZONTAL = 'Slide Horizontal'
TRANSITION_SLIDE_REVERSE_VERTICAL = 'Reverse Slide Vertical'
TRANSITION_SLIDE_REVERSE_HORIZONTAL = 'Reverse Slide Horizontal'

BING_MENU_DAY = 'Start from'
BING_MENU_MARKET = 'Location'
BING_MENU_RESOLUTION = 'Resolution'

BING_DAY_0 = 'Today'
BING_DAY_1 = 'Yesterday'
BING_DAY_2 = '2 Days Ago'
BING_DAY_3 = '3 Days Ago'
BING_DAY_4 = '4 Days Ago'
BING_DAY_5 = '5 Days Ago'
BING_DAY_6 = '6 Days Ago'
BING_DAY_7 = '7 Days Ago'

BING_RESOLUTION_800x600 = '800 × 600\tSVGA'
BING_RESOLUTION_1024x768 = '1024 × 768\t8514'
BING_RESOLUTION_1280x720 = '1280 × 720\tHD'
BING_RESOLUTION_1366x768 = '1366 × 768\tHD'
BING_RESOLUTION_1920x1200 = '1920 × 1200\tUXGA'
BING_RESOLUTION_1920x1080 = '1920 × 1080\tFHD'
BING_RESOLUTION_UHD = 'Original\tUHD'

PEXELS_LABEL_CURATED = 'Curated Photos'

PEXELS_MENU_SEARCH = 'Search Filters'
PEXELS_MENU_ORIENTATION = 'Orientation'
PEXELS_MENU_SIZE = 'Size'
PEXELS_MENU_LOCALE = 'Locale'

PEXELS_ORIENTATION_ = 'All'
PEXELS_ORIENTATION_landscape = 'Landscape'
PEXELS_ORIENTATION_portrait = 'Portrait'
PEXELS_ORIENTATION_square = 'Square'

PEXELS_SIZE_ = 'All'
PEXELS_SIZE_large = 'Large'
PEXELS_SIZE_medium = 'Medium'
PEXELS_SIZE_small = 'Small'

PEXELS_LOCALE_ = 'All'

SPOTLIGHT_MENU_LOCALE = 'Locale'
SPOTLIGHT_MENU_ORIENTATION = 'Orientation'

SPOTLIGHT_ORIENTATION_landscape = 'Landscape'
SPOTLIGHT_ORIENTATION_portrait = 'Portrait'

WALLHAVEN_MENU_CATEGORY = 'Categories'
WALLHAVEN_MENU_PURITY = 'Purities'
WALLHAVEN_MENU_SORTING = 'Sort by'
WALLHAVEN_MENU_ORDER = 'Order by'
WALLHAVEN_MENU_RANGE = 'Top List Range'
WALLHAVEN_MENU_RATIO = 'Ratio'
WALLHAVEN_MENU_COLOR = 'Color'

WALLHAVEN_CATEGORY_general = 'General'
WALLHAVEN_CATEGORY_anime = 'Anime'
WALLHAVEN_CATEGORY_people = 'People'

WALLHAVEN_PURITY_sfw = 'SFW'
WALLHAVEN_PURITY_sketchy = 'Sketchy'
WALLHAVEN_PURITY_nsfw = 'NSFW'

WALLHAVEN_SORTING_date_added = 'Date Added'
WALLHAVEN_SORTING_relevance = 'Relevance'
WALLHAVEN_SORTING_random = 'Random'
WALLHAVEN_SORTING_views = 'Views'
WALLHAVEN_SORTING_favorites = 'Favorites'
WALLHAVEN_SORTING_toplist = 'Toplist'
WALLHAVEN_SORTING_hot = 'Hot'

WALLHAVEN_ORDER_desc = 'Descending'
WALLHAVEN_ORDER_asc = 'Ascending'

WALLHAVEN_RANGE_1d = 'Last Day'
WALLHAVEN_RANGE_3d = 'Last 3 Days'
WALLHAVEN_RANGE_1w = 'Last Week'
WALLHAVEN_RANGE_1M = 'Last Month'
WALLHAVEN_RANGE_3M = 'Last 3 Months'
WALLHAVEN_RANGE_6M = 'Last 6 Months'
WALLHAVEN_RANGE_1y = 'Last Year'

WALLHAVEN_RATIO_landscape = 'All Wide'
WALLHAVEN_RATIO_16x9 = '16 × 9\tWide'
WALLHAVEN_RATIO_16x10 = '16 × 10\tWide'
WALLHAVEN_RATIO_21x9 = '21 × 9\tUltrawide'
WALLHAVEN_RATIO_32x9 = '32 × 9\tUltrawide'
WALLHAVEN_RATIO_48x9 = '48 × 9\tUltrawide'
WALLHAVEN_RATIO_portrait = 'All Portrait'
WALLHAVEN_RATIO_9x16 = '9 × 16\tPortrait'
WALLHAVEN_RATIO_10x16 = '10 × 16\tPortrait'
WALLHAVEN_RATIO_9x18 = '9 × 18\tPortrait'
WALLHAVEN_RATIO_1x1 = '1 × 1\tSquare'
WALLHAVEN_RATIO_3x2 = '3 × 2\tSquare'
WALLHAVEN_RATIO_4x3 = '4 × 3\tSquare'
WALLHAVEN_RATIO_5x4 = '5 × 4\tSquare'

WALLHAVEN_COLOR_ = 'All'
