_DIGITS = '0123456789'

DESCRIPTION = 'Python Wallpaper Changer!'
DISPLAY = 'Unknown Display'
DISPLAY_ALL = 'All Displays'
FIRST_TITLE = 'Hello from Wallpyper! 👋'
FIRST_TEXT = ('👀 See the system tray icon?\n'
              'Double click to change wallpaper,\n'
              'Right click to open context menu.')
BLOCKED_TITLE = 'Fullscreen Overlay Detected! 🚫'

LABEL_ABOUT = 'About Wallpyper'
LABEL_ANIMATE = 'Animate Tray Icon'
LABEL_AUTO_SAVE = 'Auto Save Applied Image'
LABEL_CHANGE_START = 'Change Wallpaper on Start'
LABEL_CACHE = 'Keep Wallpaper Cache'
LABEL_CHANGE = 'Change Wallpaper'
LABEL_CLEAR = 'Clear Recent List'
LABEL_CONSOLE = 'Toggle Console View'
LABEL_CLEAR_CACHE = 'Clear Wallpaper Cache'
LABEL_SETTINGS_AUTO_SAVE = 'Save Wallpyper Settings'
LABEL_COPY = 'Copy Image'
LABEL_COPY_PATH = 'Copy Image Path'
LABEL_COPY_URL = 'Copy Image URL'
LABEL_DESKTOP = 'Add to Desktop'
LABEL_NOTIFY_ERROR = 'Operation Error'
LABEL_NOTIFY_BLOCKED = 'Obscured Display'
LABEL_NO_FADE = 'Disable Wallpaper Fading'
LABEL_OPEN = 'Open Image'
LABEL_OPEN_BROWSER = 'Open Image URL'
LABEL_OPEN_EXPLORER = 'Open Image Location'
LABEL_OPEN_WITH = 'Open Image with...'
LABEL_PIN = 'Pin to Taskbar'
LABEL_PIN_START = 'Pin to Start'
LABEL_QUIT = 'Quit Wallpyper'
LABEL_REMOVE_DESKTOP = 'Remove from Desktop'
LABEL_REMOVE_START_MENU = 'Remove from Start Menu'
LABEL_SETTINGS_RESET = 'Reset Wallpyper Settings'
LABEL_RESTART = 'Restart Wallpyper'
LABEL_SAVE = 'Save Image'
LABEL_SAVE_AS = 'Save Image as...'
LABEL_SAVE_DIR = 'Saved Image Location...'
LABEL_SEARCH = 'Search Image with'
LABEL_GOOGLE = 'Google by Image'
LABEL_SET = 'Set as Wallpaper'
LABEL_SET_LOCK = 'Set as Lock Screen'
LABEL_SKIP = 'Skip Recent Wallpapers'
LABEL_REAPPLY = 'Reapply Last Wallpaper'
LABEL_RESTORE = 'Restore Last Wallpaper'
LABEL_START = 'Start at User Sign-in'
LABEL_START_MENU = 'Add to Start Menu'
LABEL_UNPIN = 'Unpin from Taskbar'
LABEL_UNPIN_START = 'Unpin from Start'
LABEL_UPDATE_DISPLAY = 'Update Display List'

LABEL_SEARCH_ALAMY = 'alamy'
LABEL_SEARCH_BING = 'Bing'
LABEL_SEARCH_GOOGLE = 'Google'
LABEL_SEARCH_GOOGLELENS = 'Google Lens'
LABEL_SEARCH_IQDB = 'IQDB'
LABEL_SEARCH_REPOSTSLEUTH = 'Repost Sleuth'
LABEL_SEARCH_SAUCENAO = 'SauceNAO'
LABEL_SEARCH_SOGOU = 'Sogou'
LABEL_SEARCH_TINEYE = 'TinEye'
LABEL_SEARCH_TRACE = 'trace.moe'
LABEL_SEARCH_YANDEX = 'Yandex'

MENU_ACTIONS = 'Wallpyper Actions'
MENU_ALIGNMENT = 'Wallpaper Alignment'
MENU_AUTO = 'Automate Wallpyper'
MENU_AUTO_CHANGE = 'Auto Change Wallpaper'
MENU_DISPLAY = 'Select Display'
MENU_FLIP = 'Flip Wallpaper'
MENU_LINKS = 'Shortcuts && Pins'
MENU_SOURCE = 'Wallpaper Source'
MENU_SOURCE_SETTINGS = 'Source Settings'
MENU_EASE = 'Easing Type'
MENU_EASE_TIMING = 'Easing Timing'
MENU_RECENT = 'Recent Wallpapers'
MENU_ROTATE = 'Rotate Wallpaper'
MENU_SETTINGS = 'Wallpyper Settings'
MENU_TRANSITION = 'Transition Animation'
MENU_TRANSITION_STYLE = 'Animation Style'
MENU_TRANSITION_DURATION = 'Animation Duration'
MENU_NOTIFICATIONS = 'Show Notifications for'
MENU_COLORS = 'Wallpyper Menu Theme'
MENU_IF_MAXIMIZED = 'If Other App Maximized'

TOOLTIP_CHANGE_START = 'Automatically change wallpaper on starting Wallpyper'
TOOLTIP_AUTO_SAVE = 'Automatically save the applied image to the selected folder'
TOOLTIP_TEMPLATE_SAVE_DIR = 'Save location: {}'

STATUS_CHANGE = 'Changing Wallpaper...'
STATUS_FETCH = 'Fetching Image List...'
STATUS_DOWNLOAD = 'Downloading Image...'
STATUS_SEARCH = 'Uploading Image...'
STATUS_QUIT = 'Quitting Wallpyper...'

FAIL_CHANGE = 'Failed changing wallpaper'
FAIL_CHANGE_LOCK = 'Failed changing lock screen'
FAIL_CLEAR = 'Failed clearing wallpaper cache'
FAIL_SHOW_CONSOLE = 'Failed opening or connecting to console'
FAIL_HIDE_CONSOLE = 'Failed closing or disconnecting from console'
FAIL_COPY = 'Failed copying image to clipboard'
FAIL_COPY_PATH = 'Failed copying image path to clipboard'
FAIL_COPY_URL = 'Failed copying image URL to clipboard'
FAIL_OPEN = 'Failed opening image in default app'
FAIL_OPEN_BROWSER = 'Failed opening image in browser'
FAIL_OPEN_EXPLORER = 'Failed opening image in Explorer'
FAIL_OPEN_WITH = 'Failed opening image with selected app'
FAIL_QUIT = 'Waiting for running tasks to be completed...'
FAIL_SAVE = 'Failed saving image'
FAIL_SAVE_DIR = 'Failed changing save location'
FAIL_SEARCH = 'Failed searching similar images'
FAIL_DESKTOP = 'Failed adding desktop shortcut'
FAIL_DESKTOP_REMOVE = 'Failed removing desktop shortcut'
FAIL_START_MENU = 'Failed adding start menu shortcut'
FAIL_START_MENU_REMOVE = 'Failed removing start menu shortcut'
FAIL_PIN = 'Failed pinning Wallpyper to taskbar'
FAIL_PIN_START = 'Failed pinning Wallpyper to start menu'
FAIL_UNPIN = 'Failed unpinning from taskbar'
FAIL_UNPIN_START = 'Failed unpinning from start menu'

INTERVAL_0 = 'Never'
INTERVAL_300 = '5 Minutes'
INTERVAL_900 = '15 Minutes'
INTERVAL_1800 = '30 Minutes'
INTERVAL_3600 = '1 Hour'
INTERVAL_10800 = '3 Hours'
INTERVAL_21600 = '6 Hours'

DURATION_0 = '0.5 Seconds'
DURATION_1 = '1 Second'
DURATION_2 = '2.5 Seconds'
DURATION_5 = '5 Seconds'
DURATION_10 = '10 Seconds'

MAXIMIZED_IGNORE = 'Ignore'
MAXIMIZED_POSTPONE = 'Postpone'
MAXIMIZED_SKIP = 'Skip'

ALIGNMENT_DEFAULT = 'Default'
ALIGNMENT_FILL = 'Fill'
ALIGNMENT_FIT = 'Fit'
ALIGNMENT_CENTER = 'Center'
ALIGNMENT_STRETCH = 'Stretch'
ALIGNMENT_TILE = 'Tile'
ALIGNMENT_SPAN = 'Span'

EASE_SINE = 'Sine'
EASE_QUAD = 'Quadratic'
EASE_CUBIC = 'Cubic'
EASE_QUART = 'Quartic'
EASE_QUINT = 'Quintic'
EASE_EXPO = 'Exponential'
EASE_CIRC = 'Circular'

EASE_DIRECTION_IN = 'Starts Slow'
EASE_DIRECTION_OUT = 'Ends Slow'

ROTATE_NONE = 'No Rotation'
ROTATE_RIGHT = 'Rotate Right'
ROTATE_LEFT = 'Rotate Left'
ROTATE_FLIP = 'Rotate 180°'

FLIP_VERTICAL = 'Vertically\tY'
FLIP_HORIZONTAL = 'Horizontally\tX'

TRANSITION_DISABLED = 'Disabled'
TRANSITION_RANDOM = 'Random'
TRANSITION_FADE = 'Fade'
TRANSITION_EXPLODE = 'Explode'
TRANSITION_IMPLODE = 'Implode'
TRANSITION_LEFT = 'Left'
TRANSITION_TOP = 'Top'
TRANSITION_RIGHT = 'Right'
TRANSITION_BOTTOM = 'Bottom'
TRANSITION_TOP_LEFT = 'Top Left'
TRANSITION_TOP_RIGHT = 'Top Right'
TRANSITION_BOTTOM_LEFT = 'Bottom Left'
TRANSITION_BOTTOM_RIGHT = 'Bottom Right'
TRANSITION_VERTICAL = 'Vertical'
TRANSITION_HORIZONTAL = 'Horizontal'
TRANSITION_REVERSE_VERTICAL = 'Vertical'
TRANSITION_REVERSE_HORIZONTAL = 'Horizontal'
TRANSITION_SLIDE_LEFT = 'Slide Left'
TRANSITION_SLIDE_TOP = 'Slide Top'
TRANSITION_SLIDE_RIGHT = 'Slide Right'
TRANSITION_SLIDE_BOTTOM = 'Slide Bottom'
TRANSITION_SLIDE_TOP_LEFT = 'Slide Top Left'
TRANSITION_SLIDE_TOP_RIGHT = 'Slide Top Right'
TRANSITION_SLIDE_BOTTOM_LEFT = 'Slide Bottom Left'
TRANSITION_SLIDE_BOTTOM_RIGHT = 'Slide Bottom Right'
TRANSITION_SLIDE_VERTICAL = 'Slide Vertical'
TRANSITION_SLIDE_HORIZONTAL = 'Slide Horizontal'
TRANSITION_SLIDE_REVERSE_VERTICAL = 'Reverse Slide Vertical'
TRANSITION_SLIDE_REVERSE_HORIZONTAL = 'Reverse Slide Horizontal'

COLOR_MODE_AUTO = 'System'
COLOR_MODE_LIGHT = 'Light'
COLOR_MODE_DARK = 'Dark'

BING_MENU_DAY = 'Start from'
BING_MENU_MARKET = 'Location'
BING_MENU_RESOLUTION = 'Resolution'

BING_DAY_0 = 'Today'
BING_DAY_1 = 'Yesterday'
BING_DAY_2 = '2 Days Ago'
BING_DAY_3 = '3 Days Ago'
BING_DAY_4 = '4 Days Ago'
BING_DAY_5 = '5 Days Ago'
BING_DAY_6 = '6 Days Ago'
BING_DAY_7 = '7 Days Ago'

BING_RESOLUTION_800x600 = '800 × 600\tSVGA'
BING_RESOLUTION_1024x768 = '1024 × 768\t8514'
BING_RESOLUTION_1280x720 = '1280 × 720\tHD'
BING_RESOLUTION_1366x768 = '1366 × 768\tHD'
BING_RESOLUTION_1920x1200 = '1920 × 1200\tUXGA'
BING_RESOLUTION_1920x1080 = '1920 × 1080\tFHD'
BING_RESOLUTION_UHD = 'Original\tUHD'

DOESNOTEXIST_MENU_VARIANT = 'Variant'

DOESNOTEXIST_VARIANT_person = 'Person'
DOESNOTEXIST_VARIANT_artwork = 'Art'
DOESNOTEXIST_VARIANT_cat = 'Cat'
DOESNOTEXIST_VARIANT_horse = 'Horse'

FIVEHUNREDPX_LEGACY_MENU_FEATURE = 'Image Feature'
FIVEHUNREDPX_LEGACY_MENU_ONLY = 'Included Categories'
FIVEHUNREDPX_LEGACY_MENU_EXCLUDE = 'Excluded Categories'
FIVEHUNREDPX_LEGACY_MENU_SORT = 'Sort Image by'
FIVEHUNREDPX_LEGACY_MENU_SORT_DIRECTION = 'Image Sort Order'

FIVEHUNREDPX_LEGACY_FEATURE_popular = 'Popular'
FIVEHUNREDPX_LEGACY_FEATURE_highest_rated = 'Highly Rated'
FIVEHUNREDPX_LEGACY_FEATURE_upcoming = 'Upcoming'
FIVEHUNREDPX_LEGACY_FEATURE_editors = 'Editor\'s Choice'
FIVEHUNREDPX_LEGACY_FEATURE_fresh_today = 'Fresh Today'
FIVEHUNREDPX_LEGACY_FEATURE_fresh_yesterday = 'Fresh Yesterday'
FIVEHUNREDPX_LEGACY_FEATURE_fresh_week = 'Fresh This Week'

FIVEHUNREDPX_LEGACY_CATEGORY_Uncategorized = 'Uncategorized'
FIVEHUNREDPX_LEGACY_CATEGORY_Abstract = 'Abstract'
FIVEHUNREDPX_LEGACY_CATEGORY_Animals = 'Animals'
FIVEHUNREDPX_LEGACY_CATEGORY_Black_and_White = 'Black and White'
FIVEHUNREDPX_LEGACY_CATEGORY_Celebrities = 'Celebrities'
FIVEHUNREDPX_LEGACY_CATEGORY_City_and_Architecture = 'City and Architecture'
FIVEHUNREDPX_LEGACY_CATEGORY_Commercial = 'Commercial'
FIVEHUNREDPX_LEGACY_CATEGORY_Concert = 'Concert'
FIVEHUNREDPX_LEGACY_CATEGORY_Family = 'Family'
FIVEHUNREDPX_LEGACY_CATEGORY_Fashion = 'Fashion'
FIVEHUNREDPX_LEGACY_CATEGORY_Film = 'Film'
FIVEHUNREDPX_LEGACY_CATEGORY_Fine_Art = 'Fine Art'
FIVEHUNREDPX_LEGACY_CATEGORY_Food = 'Food'
FIVEHUNREDPX_LEGACY_CATEGORY_Journalism = 'Journalism'
FIVEHUNREDPX_LEGACY_CATEGORY_Landscapes = 'Landscapes'
FIVEHUNREDPX_LEGACY_CATEGORY_Macro = 'Macro'
FIVEHUNREDPX_LEGACY_CATEGORY_Nature = 'Nature'
FIVEHUNREDPX_LEGACY_CATEGORY_Nude = 'Nude'
FIVEHUNREDPX_LEGACY_CATEGORY_People = 'People'
FIVEHUNREDPX_LEGACY_CATEGORY_Performing_Arts = 'Performing Arts'
FIVEHUNREDPX_LEGACY_CATEGORY_Sport = 'Sport'
FIVEHUNREDPX_LEGACY_CATEGORY_Still_Life = 'Still Life'
FIVEHUNREDPX_LEGACY_CATEGORY_Street = 'Street'
FIVEHUNREDPX_LEGACY_CATEGORY_Transportation = 'Transportation'
FIVEHUNREDPX_LEGACY_CATEGORY_Travel = 'Travel'
FIVEHUNREDPX_LEGACY_CATEGORY_Underwater = 'Underwater'
FIVEHUNREDPX_LEGACY_CATEGORY_Urban_Exploration = 'Urban Exploration'
FIVEHUNREDPX_LEGACY_CATEGORY_Wedding = 'Wedding'

FIVEHUNREDPX_LEGACY_SORT_created_at = 'Upload Time'
FIVEHUNREDPX_LEGACY_SORT_rating = 'User Rating'
FIVEHUNREDPX_LEGACY_SORT_highest_rating = 'Highest Rating'
FIVEHUNREDPX_LEGACY_SORT_times_viewed = 'Times Viewed'
FIVEHUNREDPX_LEGACY_SORT_votes_count = 'Vote Count'
FIVEHUNREDPX_LEGACY_SORT_comments_count = 'Comment Count'
FIVEHUNREDPX_LEGACY_SORT_taken_at = 'Taken Date'

FIVEHUNREDPX_LEGACY_SORT_DIRECTION_asc = 'Ascending'
FIVEHUNREDPX_LEGACY_SORT_DIRECTION_desc = 'Descending'

LOCAL_MENU_DIR = 'Choose Folder...'
LOCAL_MENU_RECURSE = 'Scan Recursively'
LOCAL_MENU_SORT = 'Sort Image by'
LOCAL_MENU_ORDER = 'Image Sort Order'

LOCAL_SORT_name = 'Name'
LOCAL_SORT_size = 'Size'
LOCAL_SORT_created = 'Creation Time'
LOCAL_SORT_modified = 'Last Modified'
LOCAL_SORT_accessed = 'Access Time'

LOCAL_ORDER_ascending = 'Ascending'
LOCAL_ORDER_descending = 'Descending'

PEXELS_LABEL_CURATED = 'Curated Photos'

PEXELS_MENU_SEARCH = 'Search Filters'
PEXELS_MENU_ORIENTATION = 'Orientation'
PEXELS_MENU_SIZE = 'Size'
PEXELS_MENU_COLOR = 'Color'
PEXELS_MENU_LOCALE = 'Locale'

PEXELS_ORIENTATION_ = 'Any'
PEXELS_ORIENTATION_landscape = 'Landscape'
PEXELS_ORIENTATION_portrait = 'Portrait'
PEXELS_ORIENTATION_square = 'Square'

PEXELS_SIZE_ = 'Any'
PEXELS_SIZE_large = 'Large'
PEXELS_SIZE_medium = 'Medium'
PEXELS_SIZE_small = 'Small'

PEXELS_COLOR_ = 'Any'
PEXELS_COLOR_red = 'Red'
PEXELS_COLOR_orange = 'Orange'
PEXELS_COLOR_yellow = 'Yellow'
PEXELS_COLOR_green = 'Green'
PEXELS_COLOR_turquoise = 'Turquoise'
PEXELS_COLOR_blue = 'Blue'
PEXELS_COLOR_violet = 'Violet'
PEXELS_COLOR_pink = 'Pink'
PEXELS_COLOR_brown = 'Brown'
PEXELS_COLOR_black = 'Black'
PEXELS_COLOR_gray = 'Gray'
PEXELS_COLOR_white = 'White'

PEXELS_LOCALE_ = 'Any'

PIXABAY_LABEL_EDITOR = 'Editor\'s Choice'
PIXABAY_LABEL_SAFE = 'SafeSearch'

PIXABAY_MENU_LANG = 'Language'
PIXABAY_MENU_TYPE = 'Image Type'
PIXABAY_MENU_ORIENTATION = 'Orientation'
PIXABAY_MENU_CATEGORY = 'Category'
PIXABAY_MENU_COLORS = 'Colors'
PIXABAY_MENU_ORDER = 'Order'

PIXABAY_TYPE_all = 'All'
PIXABAY_TYPE_photo = 'Photo'
PIXABAY_TYPE_illustration = 'Illustration'
PIXABAY_TYPE_vector = 'Vector'

PIXABAY_ORIENTATION_all = 'All'
PIXABAY_ORIENTATION_horizontal = 'Horizontal'
PIXABAY_ORIENTATION_vertical = 'Vertical'

PIXABAY_CATEGORY_ = 'Any'
PIXABAY_CATEGORY_backgrounds = 'Backgrounds'
PIXABAY_CATEGORY_fashion = 'Fashion'
PIXABAY_CATEGORY_nature = 'Nature'
PIXABAY_CATEGORY_science = 'Science'
PIXABAY_CATEGORY_education = 'Education'
PIXABAY_CATEGORY_feelings = 'Feelings'
PIXABAY_CATEGORY_health = 'Health'
PIXABAY_CATEGORY_people = 'People'
PIXABAY_CATEGORY_religion = 'Religion'
PIXABAY_CATEGORY_places = 'Places'
PIXABAY_CATEGORY_animals = 'Animals'
PIXABAY_CATEGORY_industry = 'Industry'
PIXABAY_CATEGORY_computer = 'Computer'
PIXABAY_CATEGORY_food = 'Food'
PIXABAY_CATEGORY_sports = 'Sports'
PIXABAY_CATEGORY_transportation = 'Transportation'
PIXABAY_CATEGORY_travel = 'Travel'
PIXABAY_CATEGORY_buildings = 'Buildings'
PIXABAY_CATEGORY_business = 'Business'
PIXABAY_CATEGORY_music = 'Music'

PIXABAY_COLOR_grayscale = 'Grayscale'
PIXABAY_COLOR_transparent = 'Transparent'
PIXABAY_COLOR_red = 'Red'
PIXABAY_COLOR_orange = 'Orange'
PIXABAY_COLOR_yellow = 'Yellow'
PIXABAY_COLOR_green = 'Green'
PIXABAY_COLOR_turquoise = 'Turquoise'
PIXABAY_COLOR_blue = 'Blue'
PIXABAY_COLOR_lilac = 'Lilac'
PIXABAY_COLOR_pink = 'Pink'
PIXABAY_COLOR_white = 'White'
PIXABAY_COLOR_gray = 'Gray'
PIXABAY_COLOR_black = 'Black'
PIXABAY_COLOR_brown = 'Brown'

PIXABAY_ORDER_popular = 'Popular'
PIXABAY_ORDER_latest = 'Latest'

REDDIT_LABEL_STATIC = 'Skip Animated'

REDDIT_MENU_ORIENTATIONS = 'Orientation'
REDDIT_MENU_RATINGS = 'Rating'

REDDIT_MENU_SORT = 'Sort by'
REDDIT_MENU_TIME = 'Sort Limit'

REDDIT_ORIENTATION_0 = 'Landscape'
REDDIT_ORIENTATION_1 = 'Portrait'

REDDIT_RATING_0 = 'SFW'
REDDIT_RATING_1 = 'NSFW'

REDDIT_SORT_hot = 'Hot'
REDDIT_SORT_new = 'New'
REDDIT_SORT_top = 'Top'
REDDIT_SORT_controversial = 'Controversial'
REDDIT_SORT_rising = 'Rising'

REDDIT_TIME_hour = 'Past Hour'
REDDIT_TIME_day = 'Past 24 Hours'
REDDIT_TIME_week = 'Past Week'
REDDIT_TIME_month = 'Past Month'
REDDIT_TIME_year = 'Past Year'
REDDIT_TIME_all = 'All Time'

SIMPLEDESKTOPS_LABEL_RESET = 'Reset Pagination'

SIMPLEDESKTOPS_TOOLTIP_TEMPLATE_PAGE = 'Current page: {}'

SPOTLIGHT_MENU_LOCALE = 'Locale'
SPOTLIGHT_MENU_ORIENTATION = 'Orientation'

SPOTLIGHT_ORIENTATION_landscape = 'Landscape'
SPOTLIGHT_ORIENTATION_portrait = 'Portrait'

UNSPLASH_LABEL_EDITORIAL = 'Editorial'

UNSPLASH_MENU_SEARCH = 'Search Filters'
UNSPLASH_MENU_ORDER = 'Sort by'
UNSPLASH_MENU_FILTER = 'Filter Level'
UNSPLASH_MENU_COLOR = 'Color'
UNSPLASH_MENU_ORIENTATION = 'Orientation'

UNSPLASH_ORDER_latest = 'Newest'
UNSPLASH_ORDER_oldest = 'Earliest'
UNSPLASH_ORDER_popular = 'Popularity'
UNSPLASH_ORDER_relevant = 'Relevance'

UNSPLASH_FILTER_low = 'Low'
UNSPLASH_FILTER_high = 'High'

UNSPLASH_COLOR_ = 'Any'
UNSPLASH_COLOR_black_and_white = 'Black && White'
UNSPLASH_COLOR_black = 'Black'
UNSPLASH_COLOR_white = 'White'
UNSPLASH_COLOR_yellow = 'Yellow'
UNSPLASH_COLOR_orange = 'Orange'
UNSPLASH_COLOR_red = 'Red'
UNSPLASH_COLOR_purple = 'Purple'
UNSPLASH_COLOR_magenta = 'Magenta'
UNSPLASH_COLOR_green = 'Green'
UNSPLASH_COLOR_teal = 'Teal'
UNSPLASH_COLOR_blue = 'Blue'

UNSPLASH_ORIENTATION_ = 'Any'
UNSPLASH_ORIENTATION_landscape = 'Landscape'
UNSPLASH_ORIENTATION_portrait = 'Portrait'
UNSPLASH_ORIENTATION_squarish = 'Square'

WALLHAVEN_MENU_CATEGORY = 'Categories'
WALLHAVEN_MENU_PURITY = 'Purities'
WALLHAVEN_MENU_SORTING = 'Sort by'
WALLHAVEN_MENU_ORDER = 'Order by'
WALLHAVEN_MENU_RANGE = 'Toplist Range'
WALLHAVEN_MENU_RATIO = 'Ratio'
WALLHAVEN_MENU_COLOR = 'Color'

WALLHAVEN_CATEGORY_0 = 'General'
WALLHAVEN_CATEGORY_1 = 'Anime'
WALLHAVEN_CATEGORY_2 = 'People'

WALLHAVEN_PURITY_sfw = 'SFW'
WALLHAVEN_PURITY_sketchy = 'Sketchy'
WALLHAVEN_PURITY_nsfw = 'NSFW'

WALLHAVEN_SORTING_date_added = 'Date Added'
WALLHAVEN_SORTING_relevance = 'Relevance'
WALLHAVEN_SORTING_random = 'Random'
WALLHAVEN_SORTING_views = 'Views'
WALLHAVEN_SORTING_favorites = 'Favorites'
WALLHAVEN_SORTING_toplist = 'Toplist'
WALLHAVEN_SORTING_hot = 'Hot'

WALLHAVEN_ORDER_desc = 'Descending'
WALLHAVEN_ORDER_asc = 'Ascending'

WALLHAVEN_RANGE_1d = 'Last Day'
WALLHAVEN_RANGE_3d = 'Last 3 Days'
WALLHAVEN_RANGE_1w = 'Last Week'
WALLHAVEN_RANGE_1M = 'Last Month'
WALLHAVEN_RANGE_3M = 'Last 3 Months'
WALLHAVEN_RANGE_6M = 'Last 6 Months'
WALLHAVEN_RANGE_1y = 'Last Year'

WALLHAVEN_RATIO_landscape = 'All Wide'
WALLHAVEN_RATIO_16x9 = '16 × 9\tWide'
WALLHAVEN_RATIO_16x10 = '16 × 10\tWide'
WALLHAVEN_RATIO_21x9 = '21 × 9\tUltrawide'
WALLHAVEN_RATIO_32x9 = '32 × 9\tUltrawide'
WALLHAVEN_RATIO_48x9 = '48 × 9\tUltrawide'
WALLHAVEN_RATIO_portrait = 'All Portrait'
WALLHAVEN_RATIO_9x16 = '9 × 16\tPortrait'
WALLHAVEN_RATIO_10x16 = '10 × 16\tPortrait'
WALLHAVEN_RATIO_9x18 = '9 × 18\tPortrait'
WALLHAVEN_RATIO_1x1 = '1 × 1\tSquare'
WALLHAVEN_RATIO_3x2 = '3 × 2\tSquare'
WALLHAVEN_RATIO_4x3 = '4 × 3\tSquare'
WALLHAVEN_RATIO_5x4 = '5 × 4\tSquare'

WALLHAVEN_COLOR_ = 'Any'

WALLHERE_LABEL_RANDOM = 'Random'
WALLHERE_LABEL_NSFW = 'NSFW'

WALLHERE_MENU_ORDER = 'Order by'
WALLHERE_MENU_ORIENTATION = 'Orientation'
WALLHERE_MENU_COLOR = 'Color'

WALLHERE_ORDER_latest = 'Newest / Latest'
WALLHERE_ORDER_popular = 'Hot / Popular'

WALLHERE_ORIENTATION_ = 'Any'
WALLHERE_ORIENTATION_horizontal = 'Horizontal'
WALLHERE_ORIENTATION_vertical = 'Vertical'

WALLHERE_COLOR_ = 'Any'

WALLPAPERFLARE_LABEL_SEARCH = 'Search Mode'
WALLPAPERFLARE_LABEL_MOBILE = 'Mobile Only'

WALLPAPERFLARE_MENU_SORT = 'Sort by'

WALLPAPERFLARE_SORT_ = 'Popular'
WALLPAPERFLARE_SORT_relevance = 'Relevance'

WALLPAPERSMUG_MENU_SORT = 'Sort'
WALLPAPERSMUG_MENU_TAG = 'Tag'

WALLPAPERSMUG_TAG_abstract = 'Abstract'
WALLPAPERSMUG_TAG_animals = 'Animals'
WALLPAPERSMUG_TAG_anime = 'Anime'
WALLPAPERSMUG_TAG_bike = 'Bikes'
WALLPAPERSMUG_TAG_birds = 'Birds'
WALLPAPERSMUG_TAG_cars = 'Cars'
WALLPAPERSMUG_TAG_city = 'City'
WALLPAPERSMUG_TAG_cute = 'Cute'
WALLPAPERSMUG_TAG_fantasy = 'Fantasy'
WALLPAPERSMUG_TAG_flowers = 'Flowers'
WALLPAPERSMUG_TAG_food = 'Food'
WALLPAPERSMUG_TAG_game = 'Games'
WALLPAPERSMUG_TAG_girls = 'Girls'
WALLPAPERSMUG_TAG_holiday = 'Holidays'
WALLPAPERSMUG_TAG_close_up = 'Close up'
WALLPAPERSMUG_TAG_love = 'Love'
WALLPAPERSMUG_TAG_minimal = 'Minimal'
WALLPAPERSMUG_TAG_movie = 'Movies'
WALLPAPERSMUG_TAG_nature = 'Nature'
WALLPAPERSMUG_TAG_space = 'Space'
WALLPAPERSMUG_TAG_sports = 'Sports'
WALLPAPERSMUG_TAG_superhero = 'Superhero'
WALLPAPERSMUG_TAG_texture = 'Textures'
WALLPAPERSMUG_TAG_tv_series = 'TV Series'
WALLPAPERSMUG_TAG_ = 'ALL'

WALLPAPERSMUG_SORT_latest = 'Latest'
WALLPAPERSMUG_SORT_random = 'Random'
WALLPAPERSMUG_SORT_popular = 'Popular'

YANDERE_MENU_ORIENTATIONS = 'Orientation'
YANDERE_MENU_RATINGS = 'Rating'

YANDERE_RATING_0 = 'Safe'
YANDERE_RATING_1 = 'Questionable'
YANDERE_RATING_2 = 'Explicit'

YANDERE_ORIENTATION_0 = 'Landscape'
YANDERE_ORIENTATION_1 = 'Portrait'

ZEROCHAN_MENU_SORT = 'Sort by'
ZEROCHAN_MENU_TIME = 'Sort Range'
ZEROCHAN_MENU_DIMENSION = 'Dimension'
ZEROCHAN_MENU_COLOR = 'Color'

ZEROCHAN_SORT_id = 'Recent'
ZEROCHAN_SORT_fav = 'Popular'

ZEROCHAN_TIME_0 = 'All Time'
ZEROCHAN_TIME_1 = 'Last Week'
ZEROCHAN_TIME_2 = 'Last 3 Months'

ZEROCHAN_DIMENSION_ = 'All'
ZEROCHAN_DIMENSION_large = 'Large'
ZEROCHAN_DIMENSION_huge = 'Huge'
ZEROCHAN_DIMENSION_landscape = 'Landscape'
ZEROCHAN_DIMENSION_portrait = 'Portrait'
ZEROCHAN_DIMENSION_square = 'Square'

ZEROCHAN_COLOR_ = 'Any'
ZEROCHAN_COLOR_black = 'Black'
ZEROCHAN_COLOR_blue = 'Blue'
ZEROCHAN_COLOR_brown = 'Brown'
ZEROCHAN_COLOR_green = 'Green'
ZEROCHAN_COLOR_pink = 'Pink'
ZEROCHAN_COLOR_purple = 'Purple'
ZEROCHAN_COLOR_red = 'Red'
ZEROCHAN_COLOR_white = 'White'
ZEROCHAN_COLOR_yellow = 'Yellow'
