from . import _Enum


# WebView2
# noinspection PyPep8Naming
class COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT(_Enum):
    PNG = 0
    JPEG = 1


# noinspection PyPep8Naming
class COREWEBVIEW2_COOKIE_SAME_SITE_KIND(_Enum):
    NONE = 0
    LAX = 1
    STRICT = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND(_Enum):
    DENY = 0
    ALLOW = 1
    DENY_CORS = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_SCRIPT_DIALOG_KIND(_Enum):
    ALERT = 0
    CONFIRM = 1
    PROMPT = 2
    BEFOREUNLOAD = 3


# noinspection PyPep8Naming
class COREWEBVIEW2_PROCESS_FAILED_KIND(_Enum):
    BROWSER_PROCESS_EXITED = 0
    RENDER_PROCESS_EXITED = 1
    RENDER_PROCESS_UNRESPONSIVE = 2
    FRAME_RENDER_PROCESS_EXITED = 3
    UTILITY_PROCESS_EXITED = 4
    SANDBOX_HELPER_PROCESS_EXITED = 5
    GPU_PROCESS_EXITED = 6
    PPAPI_PLUGIN_PROCESS_EXITED = 7
    PPAPI_BROKER_PROCESS_EXITED = 8
    UNKNOWN_PROCESS_EXITED = 9


# noinspection PyPep8Naming
class COREWEBVIEW2_PROCESS_FAILED_REASON(_Enum):
    UNEXPECTED = 0
    UNRESPONSIVE = 1
    TERMINATED = 2
    CRASHED = 3
    LAUNCH_FAILED = 4
    OUT_OF_MEMORY = 5
    PROFILE_DELETED = 6


# noinspection PyPep8Naming
class COREWEBVIEW2_PERMISSION_KIND(_Enum):
    UNKNOWN_PERMISSION = 0
    MICROPHONE = 1
    CAMERA = 2
    GEOLOCATION = 3
    NOTIFICATIONS = 4
    OTHER_SENSORS = 5
    CLIPBOARD_READ = 6


# noinspection PyPep8Naming
class COREWEBVIEW2_PERMISSION_STATE(_Enum):
    DEFAULT = 0
    ALLOW = 1
    DENY = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_WEB_ERROR_STATUS(_Enum):
    UNKNOWN = 0
    CERTIFICATE_COMMON_NAME_IS_INCORRECT = 1
    CERTIFICATE_EXPIRED = 2
    CLIENT_CERTIFICATE_CONTAINS_ERRORS = 3
    CERTIFICATE_REVOKED = 4
    CERTIFICATE_IS_INVALID = 5
    SERVER_UNREACHABLE = 6
    TIMEOUT = 7
    ERROR_HTTP_INVALID_SERVER_RESPONSE = 8
    CONNECTION_ABORTED = 9
    CONNECTION_RESET = 10
    DISCONNECTED = 11
    CANNOT_CONNECT = 12
    HOST_NAME_NOT_RESOLVED = 13
    OPERATION_CANCELED = 14
    REDIRECT_FAILED = 15
    UNEXPECTED_ERROR = 16
    VALID_AUTHENTICATION_CREDENTIALS_REQUIRED = 17
    VALID_PROXY_AUTHENTICATION_REQUIRED = 18


# noinspection PyPep8Naming
class COREWEBVIEW2_WEB_RESOURCE_CONTEXT(_Enum):
    ALL = 0
    DOCUMENT = 1
    STYLESHEET = 2
    IMAGE = 3
    MEDIA = 4
    FONT = 5
    SCRIPT = 6
    XML_HTTP_REQUEST = 7
    FETCH = 8
    TEXT_TRACK = 9
    EVENT_SOURCE = 10
    WEBSOCKET = 11
    MANIFEST = 12
    SIGNED_EXCHANGE = 13
    PING = 14
    CSP_VIOLATION_REPORT = 15
    OTHER = 16


# noinspection PyPep8Naming
class COREWEBVIEW2_MOVE_FOCUS_REASON(_Enum):
    PROGRAMMATIC = 0
    NEXT = 1
    PREVIOUS = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_KEY_EVENT_KIND(_Enum):
    KEY_DOWN = 0
    KEY_UP = 1
    SYSTEM_KEY_DOWN = 2
    SYSTEM_KEY_UP = 3


# noinspection PyPep8Naming
class COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND(_Enum):
    NORMAL = 0
    FAILED = 1


# noinspection PyPep8Naming
class COREWEBVIEW2_MOUSE_EVENT_KIND(_Enum):
    HORIZONTAL_WHEEL = 526
    LEFT_BUTTON_DOUBLE_CLICK = 515
    LEFT_BUTTON_DOWN = 513
    LEFT_BUTTON_UP = 514
    LEAVE = 675
    MIDDLE_BUTTON_DOUBLE_CLICK = 521
    MIDDLE_BUTTON_DOWN = 519
    MIDDLE_BUTTON_UP = 520
    MOVE = 512
    RIGHT_BUTTON_DOUBLE_CLICK = 518
    RIGHT_BUTTON_DOWN = 516
    RIGHT_BUTTON_UP = 517
    WHEEL = 522
    X_BUTTON_DOUBLE_CLICK = 525
    X_BUTTON_DOWN = 523
    X_BUTTON_UP = 524


# noinspection PyPep8Naming
class COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS(_Enum):
    NONE = 0
    LEFT_BUTTON = 1
    RIGHT_BUTTON = 2
    SHIFT = 4
    CONTROL = 8
    MIDDLE_BUTTON = 16
    X_BUTTON1 = 32
    X_BUTTON2 = 64


# noinspection PyPep8Naming
class COREWEBVIEW2_POINTER_EVENT_KIND(_Enum):
    ACTIVATE = 587
    DOWN = 582
    ENTER = 585
    LEAVE = 586
    UP = 583
    UPDATE = 581


# noinspection PyPep8Naming
class COREWEBVIEW2_BOUNDS_MODE(_Enum):
    USE_RAW_PIXELS = 0
    USE_RASTERIZATION_SCALE = 1


# noinspection PyPep8Naming
class COREWEBVIEW2_CLIENT_CERTIFICATE_KIND(_Enum):
    SMART_CARD = 0
    PIN = 1
    OTHER = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_DOWNLOAD_STATE(_Enum):
    IN_PROGRESS = 0
    INTERRUPTED = 1
    COMPLETED = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON(_Enum):
    NONE = 0
    FILE_FAILED = 1
    FILE_ACCESS_DENIED = 2
    FILE_NO_SPACE = 3
    FILE_NAME_TOO_LONG = 4
    FILE_TOO_LARGE = 5
    FILE_MALICIOUS = 6
    FILE_TRANSIENT_ERROR = 7
    FILE_BLOCKED_BY_POLICY = 8
    FILE_SECURITY_CHECK_FAILED = 9
    FILE_TOO_SHORT = 10
    FILE_HASH_MISMATCH = 11
    NETWORK_FAILED = 12
    NETWORK_TIMEOUT = 13
    NETWORK_DISCONNECTED = 14
    NETWORK_SERVER_DOWN = 15
    NETWORK_INVALID_REQUEST = 16
    SERVER_FAILED = 17
    SERVER_NO_RANGE = 18
    SERVER_BAD_CONTENT = 19
    SERVER_UNAUTHORIZED = 20
    SERVER_CERTIFICATE_PROBLEM = 21
    SERVER_FORBIDDEN = 22
    SERVER_UNEXPECTED_RESPONSE = 23
    SERVER_CONTENT_LENGTH_MISMATCH = 24
    SERVER_CROSS_ORIGIN_REDIRECT = 25
    USER_CANCELED = 26
    USER_SHUTDOWN = 27
    USER_PAUSED = 28
    DOWNLOAD_PROCESS_CRASHED = 29


# noinspection PyPep8Naming
class COREWEBVIEW2_PRINT_ORIENTATION(_Enum):
    PORTRAIT = 0
    LANDSCAPE = 1


# noinspection PyPep8Naming
class COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT(_Enum):
    TOP_LEFT = 0
    TOP_RIGHT = 1
    BOTTOM_LEFT = 2
    BOTTOM_RIGHT = 3


# noinspection PyPep8Naming
class COREWEBVIEW2_PROCESS_KIND(_Enum):
    BROWSER = 0
    RENDERER = 1
    UTILITY = 2
    SANDBOX_HELPER = 3
    GPU = 4
    PPAPI_PLUGIN = 5
    PPAPI_BROKER = 6


# noinspection PyPep8Naming
class COREWEBVIEW2_PDF_TOOLBAR_ITEMS(_Enum):
    NONE = 0
    SAVE = 1
    PRINT = 2
    SAVE_AS = 4
    ZOOM_IN = 8
    ZOOM_OUT = 16
    ROTATE = 32
    FIT_PAGE = 64
    PAGE_LAYOUT = 128
    BOOKMARKS = 256
    PAGE_SELECTOR = 512
    SEARCH = 1024
    FULL_SCREEN = 2048
    MORE_SETTINGS = 4096


# noinspection PyPep8Naming
class COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND(_Enum):
    PAGE = 0
    IMAGE = 1
    SELECTED_TEXT = 2
    AUDIO = 3
    VIDEO = 4


# noinspection PyPep8Naming
class COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND(_Enum):
    COMMAND = 0
    CHECK_BOX = 1
    RADIO = 2
    SEPARATOR = 3
    SUBMENU = 4


# noinspection PyPep8Naming
class COREWEBVIEW2_PREFERRED_COLOR_SCHEME(_Enum):
    AUTO = 0
    LIGHT = 1
    DARK = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_BROWSING_DATA_KINDS(_Enum):
    FILE_SYSTEMS = 1
    INDEXED_DB = 2
    LOCAL_STORAGE = 4
    WEB_SQL = 8
    CACHE_STORAGE = 16
    ALL_DOM_STORAGE = 32
    COOKIES = 64
    ALL_SITE = 128
    DISK_CACHE = 256
    DOWNLOAD_HISTORY = 512
    GENERAL_AUTOFILL = 1024
    PASSWORD_AUTOSAVE = 2048
    BROWSING_HISTORY = 4096
    SETTINGS = 8192
    ALL_PROFILE = 16384


# noinspection PyPep8Naming
class COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION(_Enum):
    ALWAYS_ALLOW = 0
    CANCEL = 1
    DEFAULT = 2


# noinspection PyPep8Naming
class COREWEBVIEW2_FAVICON_IMAGE_FORMAT(_Enum):
    PNG = 0
    JPEG = 1
