from __future__ import annotations as _

import enum
import ntpath
import os

from libs.ctyped.enum import CgSDK as enum_CgSDK
from libs.ctyped.lib import CgSDK_x64_2015


def _bytes(o: bytes | str | enum.Enum) -> bytes:
    if isinstance(o, enum.Enum):
        o = o.value
    if isinstance(o, str):
        o = o.encode()
    return o


def handshake() -> bool:
    details = CgSDK_x64_2015.CgSdkPerformProtocolHandshake()
    return bool(details.sdkProtocolVersion) and not details.breakingChanges


def set_game(name: bytes | str) -> bool:
    return CgSDK_x64_2015.CgSdkSetGame(_bytes(name))


def set_state(profile: bytes | str | enum.Enum) -> bool:
    return CgSDK_x64_2015.CgSdkSetState(_bytes(profile))


def set_event(profile: bytes | str | enum.Enum) -> bool:
    return CgSDK_x64_2015.CgSdkSetEvent(_bytes(profile))


def clear_state(*profiles: bytes | str | enum.Enum) -> bool:
    return (all(CgSDK_x64_2015.CgSdkClearState(profile) for profile in profiles)
            if profiles else CgSDK_x64_2015.CgSdkClearAllStates())


def clear_event() -> bool:
    return CgSDK_x64_2015.CgSdkClearAllEvents()


class _Control:
    def __init__(self):
        CgSDK_x64_2015.CgSdkRequestControl(enum_CgSDK.CorsairAccessMode.ExclusiveLightingControl)

    def __del__(self):
        CgSDK_x64_2015.CgSdkReleaseControl(enum_CgSDK.CorsairAccessMode.ExclusiveLightingControl)

    def __enter__(self):
        pass

    def __exit__(self, _, __, ___):
        self.__del__()


class _Game:
    _name: str = ''

    def __init__(self):
        self._init = handshake()
        if self._init:
            self._control = _Control()
            self._init = set_game(self._name or type(self).__name__)

    def __del__(self):
        if self:
            clear_state() and clear_event()
        self._control = None
        self._init = False

    def __bool__(self):
        return self._init

    def __enter__(self) -> _Game:
        return self

    def __exit__(self, _, __, ___):
        self.__del__()


class _Profile(enum.StrEnum):
    def __enter__(self) -> bool:
        return self.set()

    def __exit__(self, _, __, ___):
        self.clear()

    def set(self, loop: bool = True):
        return (set_state if loop else set_event)(self)

    def clear(self):
        return clear_state(self)


class AgainstTheStorm(_Game):
    class Profile(_Profile):
        ATSM_Clearance = 'ATSM_Clearance'
        ATSM_Coral = 'ATSM_Coral'
        ATSM_Drizzle = 'ATSM_Drizzle'
        ATSM_Map = 'ATSM_Map'
        ATSM_Menu = 'ATSM_Menu'
        ATSM_Storm = 'ATSM_Storm'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkOrange = 'SDKL_EnvDarkOrange'
        SDKL_EnvGreen = 'SDKL_EnvGreen'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_LootTeal = 'SDKL_LootTeal'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_PulseTan = 'SDKL_PulseTan'
        SDKL_PulseTeal = 'SDKL_PulseTeal'
        SDKL_SplashGrey = 'SDKL_SplashGrey'
        SDKL_StaticBlack = 'SDKL_StaticBlack'
        SDKL_WaterCyan = 'SDKL_WaterCyan'


class BlairWitch(_Game):
    class Profile(_Profile):
        BLW_Blackout = 'BLW_Blackout'
        BLW_Bundle = 'BLW_Bundle'
        BLW_Bye = 'BLW_Bye'
        BLW_Camera = 'BLW_Camera'
        BLW_CameraWalk = 'BLW_CameraWalk'
        BLW_Cart = 'BLW_Cart'
        BLW_Carving = 'BLW_Carving'
        BLW_Command = 'BLW_Command'
        BLW_DayBlue = 'BLW_DayBlue'
        BLW_DayGreen = 'BLW_DayGreen'
        BLW_DayGrey = 'BLW_DayGrey'
        BLW_DayYellow = 'BLW_DayYellow'
        BLW_Death = 'BLW_Death'
        BLW_FlashBlack = 'BLW_FlashBlack'
        BLW_FlashBlue = 'BLW_FlashBlue'
        BLW_FlashRed = 'BLW_FlashRed'
        BLW_FlashWhite = 'BLW_FlashWhite'
        BLW_Flashlight = 'BLW_Flashlight'
        BLW_FlashlightFlicker = 'BLW_FlashlightFlicker'
        BLW_Loading = 'BLW_Loading'
        BLW_Logo = 'BLW_Logo'
        BLW_Menu = 'BLW_Menu'
        BLW_Night = 'BLW_Night'
        BLW_Notification = 'BLW_Notification'
        BLW_Phone = 'BLW_Phone'
        BLW_Photos = 'BLW_Photos'
        BLW_PoliceLights = 'BLW_PoliceLights'
        BLW_Radio = 'BLW_Radio'
        BLW_Redout = 'BLW_Redout'
        BLW_Totem = 'BLW_Totem'
        SDKL_StaticBlack = 'SDKL_StaticBlack'
        SDKL_StaticWhite = 'SDKL_StaticWhite'


class Breakpoint(_Game):
    class Profile(_Profile):
        BKPT_Beat = 'BKPT_Beat'
        SDKL_AlertEdgesOrange = 'SDKL_AlertEdgesOrange'
        SDKL_DeathShock = 'SDKL_DeathShock'
        SDKL_EnvTech = 'SDKL_EnvTech'
        SDKL_FireworksYellowWhiteOrange = 'SDKL_FireworksYellowWhiteOrange'
        SDKL_FlashGrey = 'SDKL_FlashGrey'
        SDKL_FlashWhite = 'SDKL_FlashWhite'
        SDKL_PulseBlue = 'SDKL_PulseBlue'
        SDKL_PulseCyan = 'SDKL_PulseCyan'
        SDKL_PulseLime = 'SDKL_PulseLime'
        SDKL_PulseOrange = 'SDKL_PulseOrange'
        SDKL_PulsePink = 'SDKL_PulsePink'
        SDKL_PulsePurple = 'SDKL_PulsePurple'
        SDKL_PulseRed = 'SDKL_PulseRed'
        SDKL_PulseStarGrey = 'SDKL_PulseStarGrey'
        SDKL_RocketsBlue = 'SDKL_RocketsBlue'
        SDKL_Smoke = 'SDKL_Smoke'
        SDKL_SplashGrey = 'SDKL_SplashGrey'
        SDKL_SplashWhite = 'SDKL_SplashWhite'


class Chernobylite(_Game):
    class Profile(_Profile):
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_AlertEdgesGreen = 'SDKL_AlertEdgesGreen'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_Corrosive = 'SDKL_Corrosive'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_Fog = 'SDKL_Fog'
        SDKL_Gas = 'SDKL_Gas'
        SDKL_PulseBarGreen = 'SDKL_PulseBarGreen'
        SDKL_PulseBarRed = 'SDKL_PulseBarRed'
        SDKL_PulseStarGreen = 'SDKL_PulseStarGreen'
        SDKL_Smoke = 'SDKL_Smoke'
        SDKL_SplashRed = 'SDKL_SplashRed'
        SDKL_UnderwaterCyan = 'SDKL_UnderwaterCyan'


class Common(_Game):
    class Profile(_Profile):
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_AlertEdgesBlack = 'SDKL_AlertEdgesBlack'
        SDKL_AlertEdgesBlue = 'SDKL_AlertEdgesBlue'
        SDKL_AlertEdgesCyan = 'SDKL_AlertEdgesCyan'
        SDKL_AlertEdgesGreen = 'SDKL_AlertEdgesGreen'
        SDKL_AlertEdgesGrey = 'SDKL_AlertEdgesGrey'
        SDKL_AlertEdgesLime = 'SDKL_AlertEdgesLime'
        SDKL_AlertEdgesOrange = 'SDKL_AlertEdgesOrange'
        SDKL_AlertEdgesPink = 'SDKL_AlertEdgesPink'
        SDKL_AlertEdgesPurple = 'SDKL_AlertEdgesPurple'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_AlertEdgesWhite = 'SDKL_AlertEdgesWhite'
        SDKL_AlertEdgesYellow = 'SDKL_AlertEdgesYellow'
        SDKL_Bees = 'SDKL_Bees'
        SDKL_Bleeding = 'SDKL_Bleeding'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_Brimstone = 'SDKL_Brimstone'
        SDKL_Cobalt = 'SDKL_Cobalt'
        SDKL_Corrosive = 'SDKL_Corrosive'
        SDKL_Crimson = 'SDKL_Crimson'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_DamageCenter = 'SDKL_DamageCenter'
        SDKL_DamageClaws = 'SDKL_DamageClaws'
        SDKL_DamageSides = 'SDKL_DamageSides'
        SDKL_DamageXSlash = 'SDKL_DamageXSlash'
        SDKL_Day = 'SDKL_Day'
        SDKL_Death = 'SDKL_Death'
        SDKL_DeathExplosion = 'SDKL_DeathExplosion'
        SDKL_DeathFire = 'SDKL_DeathFire'
        SDKL_DeathGasGreen = 'SDKL_DeathGasGreen'
        SDKL_DeathShock = 'SDKL_DeathShock'
        SDKL_DeathWater = 'SDKL_DeathWater'
        SDKL_DeathWaterBlue = 'SDKL_DeathWaterBlue'
        SDKL_Downed = 'SDKL_Downed'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkYellow = 'SDKL_EnvDarkYellow'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvSunset = 'SDKL_EnvSunset'
        SDKL_EnvTech = 'SDKL_EnvTech'
        SDKL_EnvWhite = 'SDKL_EnvWhite'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_FireBlack = 'SDKL_FireBlack'
        SDKL_FireBlue = 'SDKL_FireBlue'
        SDKL_FireCyan = 'SDKL_FireCyan'
        SDKL_FireGreen = 'SDKL_FireGreen'
        SDKL_FireGrey = 'SDKL_FireGrey'
        SDKL_FireHit = 'SDKL_FireHit'
        SDKL_FireHitBlack = 'SDKL_FireHitBlack'
        SDKL_FireHitBlue = 'SDKL_FireHitBlue'
        SDKL_FireHitCyan = 'SDKL_FireHitCyan'
        SDKL_FireHitGreen = 'SDKL_FireHitGreen'
        SDKL_FireHitGrey = 'SDKL_FireHitGrey'
        SDKL_FireHitLime = 'SDKL_FireHitLime'
        SDKL_FireHitOrange = 'SDKL_FireHitOrange'
        SDKL_FireHitPink = 'SDKL_FireHitPink'
        SDKL_FireHitPurple = 'SDKL_FireHitPurple'
        SDKL_FireHitRed = 'SDKL_FireHitRed'
        SDKL_FireHitWhite = 'SDKL_FireHitWhite'
        SDKL_FireHitYellow = 'SDKL_FireHitYellow'
        SDKL_FireLime = 'SDKL_FireLime'
        SDKL_FireOrange = 'SDKL_FireOrange'
        SDKL_FirePink = 'SDKL_FirePink'
        SDKL_FirePurple = 'SDKL_FirePurple'
        SDKL_FireRed = 'SDKL_FireRed'
        SDKL_FireWhite = 'SDKL_FireWhite'
        SDKL_FireYellow = 'SDKL_FireYellow'
        SDKL_FireworksRedWhiteBlue = 'SDKL_FireworksRedWhiteBlue'
        SDKL_FlashBlack = 'SDKL_FlashBlack'
        SDKL_FlashBlue = 'SDKL_FlashBlue'
        SDKL_FlashCyan = 'SDKL_FlashCyan'
        SDKL_FlashGreen = 'SDKL_FlashGreen'
        SDKL_FlashGrey = 'SDKL_FlashGrey'
        SDKL_FlashLime = 'SDKL_FlashLime'
        SDKL_FlashOrange = 'SDKL_FlashOrange'
        SDKL_FlashPink = 'SDKL_FlashPink'
        SDKL_FlashPurple = 'SDKL_FlashPurple'
        SDKL_FlashRed = 'SDKL_FlashRed'
        SDKL_FlashWhite = 'SDKL_FlashWhite'
        SDKL_FlashYellow = 'SDKL_FlashYellow'
        SDKL_Flashlight = 'SDKL_Flashlight'
        SDKL_FlyingDown = 'SDKL_FlyingDown'
        SDKL_FlyingUp = 'SDKL_FlyingUp'
        SDKL_Fog = 'SDKL_Fog'
        SDKL_GasGreen = 'SDKL_GasGreen'
        SDKL_GlowBlack = 'SDKL_GlowBlack'
        SDKL_GlowBlue = 'SDKL_GlowBlue'
        SDKL_GlowCyan = 'SDKL_GlowCyan'
        SDKL_GlowGreen = 'SDKL_GlowGreen'
        SDKL_GlowGrey = 'SDKL_GlowGrey'
        SDKL_GlowLime = 'SDKL_GlowLime'
        SDKL_GlowOrange = 'SDKL_GlowOrange'
        SDKL_GlowPink = 'SDKL_GlowPink'
        SDKL_GlowPurple = 'SDKL_GlowPurple'
        SDKL_GlowRed = 'SDKL_GlowRed'
        SDKL_GlowWhite = 'SDKL_GlowWhite'
        SDKL_GlowYellow = 'SDKL_GlowYellow'
        SDKL_Healing = 'SDKL_Healing'
        SDKL_HeartPink = 'SDKL_HeartPink'
        SDKL_HeartRed = 'SDKL_HeartRed'
        SDKL_HintBlack = 'SDKL_HintBlack'
        SDKL_HintBlue = 'SDKL_HintBlue'
        SDKL_HintCyan = 'SDKL_HintCyan'
        SDKL_HintGreen = 'SDKL_HintGreen'
        SDKL_HintGrey = 'SDKL_HintGrey'
        SDKL_HintLime = 'SDKL_HintLime'
        SDKL_HintOrange = 'SDKL_HintOrange'
        SDKL_HintPink = 'SDKL_HintPink'
        SDKL_HintPurple = 'SDKL_HintPurple'
        SDKL_HintRed = 'SDKL_HintRed'
        SDKL_HintWhite = 'SDKL_HintWhite'
        SDKL_HintYellow = 'SDKL_HintYellow'
        SDKL_Ice = 'SDKL_Ice'
        SDKL_IceHit = 'SDKL_IceHit'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_LightningStrike = 'SDKL_LightningStrike'
        SDKL_LootBlack = 'SDKL_LootBlack'
        SDKL_LootBlue = 'SDKL_LootBlue'
        SDKL_LootCyan = 'SDKL_LootCyan'
        SDKL_LootGold = 'SDKL_LootGold'
        SDKL_LootGreen = 'SDKL_LootGreen'
        SDKL_LootGrey = 'SDKL_LootGrey'
        SDKL_LootLime = 'SDKL_LootLime'
        SDKL_LootOrange = 'SDKL_LootOrange'
        SDKL_LootPink = 'SDKL_LootPink'
        SDKL_LootPurple = 'SDKL_LootPurple'
        SDKL_LootRed = 'SDKL_LootRed'
        SDKL_LootWhite = 'SDKL_LootWhite'
        SDKL_LootYellow = 'SDKL_LootYellow'
        SDKL_Melee = 'SDKL_Melee'
        SDKL_MushroomCloud = 'SDKL_MushroomCloud'
        SDKL_Neon = 'SDKL_Neon'
        SDKL_Night = 'SDKL_Night'
        SDKL_NightDark = 'SDKL_NightDark'
        SDKL_Nuclear = 'SDKL_Nuclear'
        SDKL_Overheat = 'SDKL_Overheat'
        SDKL_PillarsBlack = 'SDKL_PillarsBlack'
        SDKL_PillarsBlue = 'SDKL_PillarsBlue'
        SDKL_PillarsCyan = 'SDKL_PillarsCyan'
        SDKL_PillarsGreen = 'SDKL_PillarsGreen'
        SDKL_PillarsGrey = 'SDKL_PillarsGrey'
        SDKL_PillarsLime = 'SDKL_PillarsLime'
        SDKL_PillarsOrange = 'SDKL_PillarsOrange'
        SDKL_PillarsPink = 'SDKL_PillarsPink'
        SDKL_PillarsPurple = 'SDKL_PillarsPurple'
        SDKL_PillarsRed = 'SDKL_PillarsRed'
        SDKL_PillarsWhite = 'SDKL_PillarsWhite'
        SDKL_PillarsYellow = 'SDKL_PillarsYellow'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_PoisonGreen = 'SDKL_PoisonGreen'
        SDKL_PoliceLightsFull = 'SDKL_PoliceLightsFull'
        SDKL_PowerOn = 'SDKL_PowerOn'
        SDKL_PulseBarBlack = 'SDKL_PulseBarBlack'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseBarCyan = 'SDKL_PulseBarCyan'
        SDKL_PulseBarGreen = 'SDKL_PulseBarGreen'
        SDKL_PulseBarGrey = 'SDKL_PulseBarGrey'
        SDKL_PulseBarLime = 'SDKL_PulseBarLime'
        SDKL_PulseBarOrange = 'SDKL_PulseBarOrange'
        SDKL_PulseBarPink = 'SDKL_PulseBarPink'
        SDKL_PulseBarPurple = 'SDKL_PulseBarPurple'
        SDKL_PulseBarRed = 'SDKL_PulseBarRed'
        SDKL_PulseBarWhite = 'SDKL_PulseBarWhite'
        SDKL_PulseBarYellow = 'SDKL_PulseBarYellow'
        SDKL_PulseBlack = 'SDKL_PulseBlack'
        SDKL_PulseBlue = 'SDKL_PulseBlue'
        SDKL_PulseCyan = 'SDKL_PulseCyan'
        SDKL_PulseGreen = 'SDKL_PulseGreen'
        SDKL_PulseGrey = 'SDKL_PulseGrey'
        SDKL_PulseLime = 'SDKL_PulseLime'
        SDKL_PulseOrange = 'SDKL_PulseOrange'
        SDKL_PulsePink = 'SDKL_PulsePink'
        SDKL_PulsePurple = 'SDKL_PulsePurple'
        SDKL_PulseRed = 'SDKL_PulseRed'
        SDKL_PulseStarBlack = 'SDKL_PulseStarBlack'
        SDKL_PulseStarBlue = 'SDKL_PulseStarBlue'
        SDKL_PulseStarCyan = 'SDKL_PulseStarCyan'
        SDKL_PulseStarGreen = 'SDKL_PulseStarGreen'
        SDKL_PulseStarGrey = 'SDKL_PulseStarGrey'
        SDKL_PulseStarLime = 'SDKL_PulseStarLime'
        SDKL_PulseStarOrange = 'SDKL_PulseStarOrange'
        SDKL_PulseStarPink = 'SDKL_PulseStarPink'
        SDKL_PulseStarPurple = 'SDKL_PulseStarPurple'
        SDKL_PulseStarRed = 'SDKL_PulseStarRed'
        SDKL_PulseStarWhite = 'SDKL_PulseStarWhite'
        SDKL_PulseStarYellow = 'SDKL_PulseStarYellow'
        SDKL_PulseWhite = 'SDKL_PulseWhite'
        SDKL_PulseYellow = 'SDKL_PulseYellow'
        SDKL_Radioactive = 'SDKL_Radioactive'
        SDKL_Rain = 'SDKL_Rain'
        SDKL_RangeHit = 'SDKL_RangeHit'
        SDKL_RocketsBlue = 'SDKL_RocketsBlue'
        SDKL_RocketsOrange = 'SDKL_RocketsOrange'
        SDKL_Shadow = 'SDKL_Shadow'
        SDKL_ShapeSpinWhite = 'SDKL_ShapeSpinWhite'
        SDKL_ShockBlack = 'SDKL_ShockBlack'
        SDKL_ShockBlue = 'SDKL_ShockBlue'
        SDKL_ShockCyan = 'SDKL_ShockCyan'
        SDKL_ShockGreen = 'SDKL_ShockGreen'
        SDKL_ShockGrey = 'SDKL_ShockGrey'
        SDKL_ShockLime = 'SDKL_ShockLime'
        SDKL_ShockOrange = 'SDKL_ShockOrange'
        SDKL_ShockPink = 'SDKL_ShockPink'
        SDKL_ShockPurple = 'SDKL_ShockPurple'
        SDKL_ShockRed = 'SDKL_ShockRed'
        SDKL_ShockWhite = 'SDKL_ShockWhite'
        SDKL_ShockYellow = 'SDKL_ShockYellow'
        SDKL_Smoke = 'SDKL_Smoke'
        SDKL_Snow = 'SDKL_Snow'
        SDKL_SonarBlack = 'SDKL_SonarBlack'
        SDKL_SonarBlue = 'SDKL_SonarBlue'
        SDKL_SonarCyan = 'SDKL_SonarCyan'
        SDKL_SonarGreen = 'SDKL_SonarGreen'
        SDKL_SonarGrey = 'SDKL_SonarGrey'
        SDKL_SonarLime = 'SDKL_SonarLime'
        SDKL_SonarOrange = 'SDKL_SonarOrange'
        SDKL_SonarPink = 'SDKL_SonarPink'
        SDKL_SonarPurple = 'SDKL_SonarPurple'
        SDKL_SonarRed = 'SDKL_SonarRed'
        SDKL_SonarWhite = 'SDKL_SonarWhite'
        SDKL_SonarYellow = 'SDKL_SonarYellow'
        SDKL_SparksBlack = 'SDKL_SparksBlack'
        SDKL_SparksBlue = 'SDKL_SparksBlue'
        SDKL_SparksCyan = 'SDKL_SparksCyan'
        SDKL_SparksGreen = 'SDKL_SparksGreen'
        SDKL_SparksGrey = 'SDKL_SparksGrey'
        SDKL_SparksLime = 'SDKL_SparksLime'
        SDKL_SparksOrange = 'SDKL_SparksOrange'
        SDKL_SparksPink = 'SDKL_SparksPink'
        SDKL_SparksPurple = 'SDKL_SparksPurple'
        SDKL_SparksRed = 'SDKL_SparksRed'
        SDKL_SparksWhite = 'SDKL_SparksWhite'
        SDKL_SparksYellow = 'SDKL_SparksYellow'
        SDKL_SplashBlack = 'SDKL_SplashBlack'
        SDKL_SplashBlue = 'SDKL_SplashBlue'
        SDKL_SplashCyan = 'SDKL_SplashCyan'
        SDKL_SplashGreen = 'SDKL_SplashGreen'
        SDKL_SplashGrey = 'SDKL_SplashGrey'
        SDKL_SplashLime = 'SDKL_SplashLime'
        SDKL_SplashOrange = 'SDKL_SplashOrange'
        SDKL_SplashPink = 'SDKL_SplashPink'
        SDKL_SplashPurple = 'SDKL_SplashPurple'
        SDKL_SplashRed = 'SDKL_SplashRed'
        SDKL_SplashWhite = 'SDKL_SplashWhite'
        SDKL_SplashYellow = 'SDKL_SplashYellow'
        SDKL_Spotted = 'SDKL_Spotted'
        SDKL_StaticBlack = 'SDKL_StaticBlack'
        SDKL_StaticBlue = 'SDKL_StaticBlue'
        SDKL_StaticCyan = 'SDKL_StaticCyan'
        SDKL_StaticGreen = 'SDKL_StaticGreen'
        SDKL_StaticGrey = 'SDKL_StaticGrey'
        SDKL_StaticLime = 'SDKL_StaticLime'
        SDKL_StaticOrange = 'SDKL_StaticOrange'
        SDKL_StaticPink = 'SDKL_StaticPink'
        SDKL_StaticPurple = 'SDKL_StaticPurple'
        SDKL_StaticRed = 'SDKL_StaticRed'
        SDKL_StaticWhite = 'SDKL_StaticWhite'
        SDKL_StaticYellow = 'SDKL_StaticYellow'
        SDKL_Suffocate = 'SDKL_Suffocate'
        SDKL_TVNoise = 'SDKL_TVNoise'
        SDKL_Titanium = 'SDKL_Titanium'
        SDKL_Underwater = 'SDKL_Underwater'
        SDKL_UnderwaterBlue = 'SDKL_UnderwaterBlue'
        SDKL_Water = 'SDKL_Water'
        SDKL_WaterBlue = 'SDKL_WaterBlue'
        SDKL_WaterBrown = 'SDKL_WaterBrown'
        SDKL_WaterHit = 'SDKL_WaterHit'
        SDKL_WaterHitBlue = 'SDKL_WaterHitBlue'
        SDKL_WaveDownBlack = 'SDKL_WaveDownBlack'
        SDKL_WaveDownBlue = 'SDKL_WaveDownBlue'
        SDKL_WaveDownCyan = 'SDKL_WaveDownCyan'
        SDKL_WaveDownGreen = 'SDKL_WaveDownGreen'
        SDKL_WaveDownGrey = 'SDKL_WaveDownGrey'
        SDKL_WaveDownLime = 'SDKL_WaveDownLime'
        SDKL_WaveDownOrange = 'SDKL_WaveDownOrange'
        SDKL_WaveDownPink = 'SDKL_WaveDownPink'
        SDKL_WaveDownPurple = 'SDKL_WaveDownPurple'
        SDKL_WaveDownRed = 'SDKL_WaveDownRed'
        SDKL_WaveDownWhite = 'SDKL_WaveDownWhite'
        SDKL_WaveDownYellow = 'SDKL_WaveDownYellow'
        SDKL_WaveLeftBlack = 'SDKL_WaveLeftBlack'
        SDKL_WaveLeftBlue = 'SDKL_WaveLeftBlue'
        SDKL_WaveLeftCyan = 'SDKL_WaveLeftCyan'
        SDKL_WaveLeftGreen = 'SDKL_WaveLeftGreen'
        SDKL_WaveLeftGrey = 'SDKL_WaveLeftGrey'
        SDKL_WaveLeftLime = 'SDKL_WaveLeftLime'
        SDKL_WaveLeftOrange = 'SDKL_WaveLeftOrange'
        SDKL_WaveLeftPink = 'SDKL_WaveLeftPink'
        SDKL_WaveLeftPurple = 'SDKL_WaveLeftPurple'
        SDKL_WaveLeftRed = 'SDKL_WaveLeftRed'
        SDKL_WaveLeftWhite = 'SDKL_WaveLeftWhite'
        SDKL_WaveLeftYellow = 'SDKL_WaveLeftYellow'
        SDKL_WaveRightBlack = 'SDKL_WaveRightBlack'
        SDKL_WaveRightBlue = 'SDKL_WaveRightBlue'
        SDKL_WaveRightCyan = 'SDKL_WaveRightCyan'
        SDKL_WaveRightGreen = 'SDKL_WaveRightGreen'
        SDKL_WaveRightGrey = 'SDKL_WaveRightGrey'
        SDKL_WaveRightLime = 'SDKL_WaveRightLime'
        SDKL_WaveRightOrange = 'SDKL_WaveRightOrange'
        SDKL_WaveRightPink = 'SDKL_WaveRightPink'
        SDKL_WaveRightPurple = 'SDKL_WaveRightPurple'
        SDKL_WaveRightRed = 'SDKL_WaveRightRed'
        SDKL_WaveRightWhite = 'SDKL_WaveRightWhite'
        SDKL_WaveRightYellow = 'SDKL_WaveRightYellow'
        SDKL_WaveUpBlack = 'SDKL_WaveUpBlack'
        SDKL_WaveUpBlue = 'SDKL_WaveUpBlue'
        SDKL_WaveUpCyan = 'SDKL_WaveUpCyan'
        SDKL_WaveUpGreen = 'SDKL_WaveUpGreen'
        SDKL_WaveUpGrey = 'SDKL_WaveUpGrey'
        SDKL_WaveUpLime = 'SDKL_WaveUpLime'
        SDKL_WaveUpOrange = 'SDKL_WaveUpOrange'
        SDKL_WaveUpPink = 'SDKL_WaveUpPink'
        SDKL_WaveUpPurple = 'SDKL_WaveUpPurple'
        SDKL_WaveUpRed = 'SDKL_WaveUpRed'
        SDKL_WaveUpWhite = 'SDKL_WaveUpWhite'
        SDKL_WaveUpYellow = 'SDKL_WaveUpYellow'
        SDKL_WipeWhite = 'SDKL_WipeWhite'


class CoreKeeper(_Game):
    class Profile(_Profile):
        CORE_Inventory = 'CORE_Inventory'
        CORE_Menu = 'CORE_Menu'
        CORE_Mold = 'CORE_Mold'
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvTech = 'SDKL_EnvTech'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_Lava = 'SDKL_Lava'
        SDKL_LootOrange = 'SDKL_LootOrange'
        SDKL_LootPurple = 'SDKL_LootPurple'
        SDKL_PillarsBlue = 'SDKL_PillarsBlue'
        SDKL_PulseBlue = 'SDKL_PulseBlue'
        SDKL_PulseStarBlue = 'SDKL_PulseStarBlue'
        SDKL_PulseStarCyan = 'SDKL_PulseStarCyan'
        SDKL_ShockBlue = 'SDKL_ShockBlue'
        SDKL_SplashBlue = 'SDKL_SplashBlue'
        SDKL_UnderwaterBlue = 'SDKL_UnderwaterBlue'
        SDKL_WaveDownBlue = 'SDKL_WaveDownBlue'
        SDKL_WaveUpGreen = 'SDKL_WaveUpGreen'


class Dwerve(_Game):
    class Profile(_Profile):
        DWVE_Build = 'DWVE_Build'
        DWVE_Combat = 'DWVE_Combat'
        DWVE_Menu = 'DWVE_Menu'
        DWVE_Recall = 'DWVE_Recall'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_Crimson = 'SDKL_Crimson'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkPurple = 'SDKL_EnvDarkPurple'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_FadeToGrey = 'SDKL_FadeToGrey'
        SDKL_FireworksYellowWhiteOrange = 'SDKL_FireworksYellowWhiteOrange'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_LootBlue = 'SDKL_LootBlue'
        SDKL_LootGold = 'SDKL_LootGold'
        SDKL_LootGrey = 'SDKL_LootGrey'
        SDKL_LootRed = 'SDKL_LootRed'
        SDKL_PillarsWhite = 'SDKL_PillarsWhite'
        SDKL_PulseBarOrange = 'SDKL_PulseBarOrange'
        SDKL_PulseStarOrange = 'SDKL_PulseStarOrange'
        SDKL_SplashLime = 'SDKL_SplashLime'
        SDKL_WaveDownGreen = 'SDKL_WaveDownGreen'
        SDKL_WaveUpRed = 'SDKL_WaveUpRed'


class Embr(_Game):
    class Profile(_Profile):
        EMBR_Default = 'EMBR_Default'
        EMBR_Findr = 'EMBR_Findr'
        EMBR_Logo = 'EMBR_Logo'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_Corrosive = 'SDKL_Corrosive'
        SDKL_Death = 'SDKL_Death'
        SDKL_Downed = 'SDKL_Downed'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_FlashYellow = 'SDKL_FlashYellow'
        SDKL_FlyingDown = 'SDKL_FlyingDown'
        SDKL_FlyingUp = 'SDKL_FlyingUp'
        SDKL_HeartRed = 'SDKL_HeartRed'
        SDKL_PulseBarWhite = 'SDKL_PulseBarWhite'
        SDKL_ShockYellow = 'SDKL_ShockYellow'
        SDKL_WaterBlue = 'SDKL_WaterBlue'


class FarCryNewDawn(_Game):
    _name = 'Far Cry New Dawn'

    class Profile(_Profile):
        FCDN_Loot = 'FCDN_Loot'
        FCND_Base = 'FCND_Base'
        FCND_BaseStation = 'FCND_BaseStation'
        FCND_Bonfire = 'FCND_Bonfire'
        FCND_Craft = 'FCND_Craft'
        FCND_Credits = 'FCND_Credits'
        FCND_Danger = 'FCND_Danger'
        FCND_Day = 'FCND_Day'
        FCND_ExpedEnd = 'FCND_ExpedEnd'
        FCND_ExpedStart = 'FCND_ExpedStart'
        FCND_Father = 'FCND_Father'
        FCND_FireHitPink = 'FCND_FireHitPink'
        FCND_FlyDay = 'FCND_FlyDay'
        FCND_FlyNight = 'FCND_FlyNight'
        FCND_GFH = 'FCND_GFH'
        FCND_GFHCom = 'FCND_GFHCom'
        FCND_Indoors = 'FCND_Indoors'
        FCND_ItemEpic = 'FCND_ItemEpic'
        FCND_ItemLegend = 'FCND_ItemLegend'
        FCND_ItemRare = 'FCND_ItemRare'
        FCND_Liberty = 'FCND_Liberty'
        FCND_Menu = 'FCND_Menu'
        FCND_Night = 'FCND_Night'
        FCND_NorthDay = 'FCND_NorthDay'
        FCND_Sisters = 'FCND_Sisters'
        FCND_Symbol = 'FCND_Symbol'
        FCND_TheNorth = 'FCND_TheNorth'
        FC_Bees = 'FC_Bees'
        FC_Benchmark = 'FC_Benchmark'
        FC_Death = 'FC_Death'
        FC_Drug = 'FC_Drug'
        FC_Drunk = 'FC_Drunk'
        FC_Fish = 'FC_Fish'
        FC_Spotted = 'FC_Spotted'
        FC_Takedown = 'FC_Takedown'
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_Claws = 'SDKL_Claws'
        SDKL_Corrosive = 'SDKL_Corrosive'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_FireHit = 'SDKL_FireHit'
        SDKL_FlashRed = 'SDKL_FlashRed'
        SDKL_FlashWhite = 'SDKL_FlashWhite'
        SDKL_FlashYellow = 'SDKL_FlashYellow'
        SDKL_GlowOrange = 'SDKL_GlowOrange'
        SDKL_Healing = 'SDKL_Healing'
        SDKL_Melee = 'SDKL_Melee'
        SDKL_MushroomCloud = 'SDKL_MushroomCloud'
        SDKL_PoisonGreen = 'SDKL_PoisonGreen'
        SDKL_PulseGreen = 'SDKL_PulseGreen'
        SDKL_PulsePink = 'SDKL_PulsePink'
        SDKL_PulseWhite = 'SDKL_PulseWhite'
        SDKL_PulseYellow = 'SDKL_PulseYellow'
        SDKL_RangeHit = 'SDKL_RangeHit'
        SDKL_Shadow = 'SDKL_Shadow'
        SDKL_Underwater = 'SDKL_Underwater'
        SDKL_Water = 'SDKL_Water'


class FarCry5(_Game):
    class Profile(_Profile):
        FCHOD_Day = 'FCHOD_Day'
        FCHOD_Liberty = 'FCHOD_Liberty'
        FCHOD_Menu = 'FCHOD_Menu'
        FCLOM_BroBot = 'FCLOM_BroBot'
        FCLOM_DustCloud = 'FCLOM_DustCloud'
        FCLOM_Exterior = 'FCLOM_Exterior'
        FCLOM_GravityBelt = 'FCLOM_GravityBelt'
        FCLOM_Hemoleum = 'FCLOM_Hemoleum'
        FCLOM_Intertior = 'FCLOM_Intertior'
        FCLOM_Menu = 'FCLOM_Menu'
        FCLOM_Overheat = 'FCLOM_Overheat'
        FCLOM_PowerOn = 'FCLOM_PowerOn'
        FCLOM_QueenKill = 'FCLOM_QueenKill'
        FCLOM_Restored = 'FCLOM_Restored'
        FCLOM_SpaceWings = 'FCLOM_SpaceWings'
        FC_AnimalAttack = 'FC_AnimalAttack'
        FC_Arcade = 'FC_Arcade'
        FC_ArcadeCoin = 'FC_ArcadeCoin'
        FC_ArcadeMenu = 'FC_ArcadeMenu'
        FC_Bees = 'FC_Bees'
        FC_Benchmark = 'FC_Benchmark'
        FC_Bliss = 'FC_Bliss'
        FC_CrouchDay = 'FC_CrouchDay'
        FC_CrouchNight = 'FC_CrouchNight'
        FC_Cutscene = 'FC_Cutscene'
        FC_Day = 'FC_Day'
        FC_Death = 'FC_Death'
        FC_Down = 'FC_Down'
        FC_Drug = 'FC_Drug'
        FC_Drunk = 'FC_Drunk'
        FC_Equip = 'FC_Equip'
        FC_Explosion = 'FC_Explosion'
        FC_Fire = 'FC_Fire'
        FC_FireFlag = 'FC_FireFlag'
        FC_Fish = 'FC_Fish'
        FC_FlightDay = 'FC_FlightDay'
        FC_FlightNight = 'FC_FlightNight'
        FC_FlyRaceCheckpoint = 'FC_FlyRaceCheckpoint'
        FC_Liberty = 'FC_Liberty'
        FC_LibertyBlue = 'FC_LibertyBlue'
        FC_LibertyFlag = 'FC_LibertyFlag'
        FC_MPLoss = 'FC_MPLoss'
        FC_MPWin = 'FC_MPWin'
        FC_Melee = 'FC_Melee'
        FC_Menu = 'FC_Menu'
        FC_Night = 'FC_Night'
        FC_NightLight = 'FC_NightLight'
        FC_Psychedelic = 'FC_Psychedelic'
        FC_RaceCheckpoint = 'FC_RaceCheckpoint'
        FC_Shoot = 'FC_Shoot'
        FC_Skunk = 'FC_Skunk'
        FC_Spotted = 'FC_Spotted'
        FC_Takedown = 'FC_Takedown'
        FC_Underwater = 'FC_Underwater'
        FC_Water = 'FC_Water'


class FarCry6(_Game):
    class Profile(_Profile):
        FC6_Death = 'FC6_Death'
        FC6_EnvCity = 'FC6_EnvCity'
        FC6_EnvFlight = 'FC6_EnvFlight'
        FC6_EnvOutside = 'FC6_EnvOutside'
        FC6_EnvUnderground = 'FC6_EnvUnderground'
        FC6_EnvVillage = 'FC6_EnvVillage'
        FC6_EnvWater = 'FC6_EnvWater'
        FC6_Horn = 'FC6_Horn'
        FC6_Liberated = 'FC6_Liberated'
        FC6_MatchLost = 'FC6_MatchLost'
        FC6_MatchWon = 'FC6_MatchWon'
        FC6_MenuDark = 'FC6_MenuDark'
        FC6_MenuLight = 'FC6_MenuLight'
        FC6_MenuMain = 'FC6_MenuMain'
        FC6_MenuMap = 'FC6_MenuMap'
        FC6_MenuMission = 'FC6_MenuMission'
        FC6_Mission = 'FC6_Mission'
        FC6_Phone = 'FC6_Phone'
        FC6_Spotted = 'FC6_Spotted'
        FC6_TimeDawn = 'FC6_TimeDawn'
        FC6_TimeDay = 'FC6_TimeDay'
        FC6_TimeDusk = 'FC6_TimeDusk'
        FC6_TimeNight = 'FC6_TimeNight'
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_AlertEdgesPurple = 'SDKL_AlertEdgesPurple'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_DamageSides = 'SDKL_DamageSides'
        SDKL_Downed = 'SDKL_Downed'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_FireRed = 'SDKL_FireRed'
        SDKL_FlashGreen = 'SDKL_FlashGreen'
        SDKL_FlashWhite = 'SDKL_FlashWhite'
        SDKL_Flashlight = 'SDKL_Flashlight'
        SDKL_HintBlue = 'SDKL_HintBlue'
        SDKL_HintGreen = 'SDKL_HintGreen'
        SDKL_HintRed = 'SDKL_HintRed'
        SDKL_HintYellow = 'SDKL_HintYellow'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_LightningStrike = 'SDKL_LightningStrike'
        SDKL_Melee = 'SDKL_Melee'
        SDKL_Rain = 'SDKL_Rain'
        SDKL_StaticBlack = 'SDKL_StaticBlack'
        SDKL_StaticBlue = 'SDKL_StaticBlue'
        SDKL_StaticCyan = 'SDKL_StaticCyan'
        SDKL_StaticGreen = 'SDKL_StaticGreen'
        SDKL_StaticRed = 'SDKL_StaticRed'
        SDKL_StaticYellow = 'SDKL_StaticYellow'
        SDKL_WaterBlue = 'SDKL_WaterBlue'
        SDKL_WaveUpRed = 'SDKL_WaveUpRed'
        SDKL_WaveUpYellow = 'SDKL_WaveUpYellow'


class FreshlyFrosted(_Game):
    class Profile(_Profile):
        FRFR_Menu = 'FRFR_Menu'
        FRFR_Play_World01 = 'FRFR_Play_World01'
        FRFR_Play_World02 = 'FRFR_Play_World02'
        FRFR_Play_World03 = 'FRFR_Play_World03'
        FRFR_Play_World04 = 'FRFR_Play_World04'
        FRFR_Play_World05 = 'FRFR_Play_World05'
        FRFR_Play_World06 = 'FRFR_Play_World06'
        FRFR_Play_World07 = 'FRFR_Play_World07'
        FRFR_Play_World08 = 'FRFR_Play_World08'
        FRFR_Play_World09 = 'FRFR_Play_World09'
        FRFR_Play_World10 = 'FRFR_Play_World10'
        FRFR_Play_World11 = 'FRFR_Play_World11'
        FRFR_Play_World12 = 'FRFR_Play_World12'
        FRFR_World01 = 'FRFR_World01'
        FRFR_World02 = 'FRFR_World02'
        FRFR_World03 = 'FRFR_World03'
        FRFR_World04 = 'FRFR_World04'
        FRFR_World05 = 'FRFR_World05'
        FRFR_World06 = 'FRFR_World06'
        FRFR_World07 = 'FRFR_World07'
        FRFR_World08 = 'FRFR_World08'
        FRFR_World09 = 'FRFR_World09'
        FRFR_World10 = 'FRFR_World10'
        FRFR_World11 = 'FRFR_World11'
        FRFR_World12 = 'FRFR_World12'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_LootWhite = 'SDKL_LootWhite'
        SDKL_StaticBlack = 'SDKL_StaticBlack'


class Gamedec(_Game):
    class Profile(_Profile):
        GMDC_InterrogationBase = 'GMDC_InterrogationBase'
        GMDC_InterrogationOne = 'GMDC_InterrogationOne'
        GMDC_InterrogationTwo = 'GMDC_InterrogationTwo'
        GMDC_Menu = 'GMDC_Menu'
        SDKL_Crimson = 'SDKL_Crimson'
        SDKL_Day = 'SDKL_Day'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvSunset = 'SDKL_EnvSunset'
        SDKL_EnvTech = 'SDKL_EnvTech'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_FireHit = 'SDKL_FireHit'
        SDKL_FireworksYellowWhiteBlue = 'SDKL_FireworksYellowWhiteBlue'
        SDKL_HeartRed = 'SDKL_HeartRed'
        SDKL_LootBlue = 'SDKL_LootBlue'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseBarGreen = 'SDKL_PulseBarGreen'
        SDKL_PulseBarRed = 'SDKL_PulseBarRed'
        SDKL_PulseBarYellow = 'SDKL_PulseBarYellow'
        SDKL_PulseOrange = 'SDKL_PulseOrange'
        SDKL_PulseStarGreen = 'SDKL_PulseStarGreen'
        SDKL_SplashBlue = 'SDKL_SplashBlue'
        SDKL_SplashYellow = 'SDKL_SplashYellow'
        SDKL_WaveDownBlue = 'SDKL_WaveDownBlue'
        SDKL_WaveDownGreen = 'SDKL_WaveDownGreen'
        SDKL_WaveDownPink = 'SDKL_WaveDownPink'
        SDKL_WaveDownPurple = 'SDKL_WaveDownPurple'
        SDKL_WaveDownYellow = 'SDKL_WaveDownYellow'
        SDKL_WaveUpGreen = 'SDKL_WaveUpGreen'


class Ghostrunner(_Game):
    class Profile(_Profile):
        GHST_Blink = 'GHST_Blink'
        GHST_CyberVoid = 'GHST_CyberVoid'
        GHST_CyberVoidDestination = 'GHST_CyberVoidDestination'
        GHST_CyberVoidRed = 'GHST_CyberVoidRed'
        GHST_Death = 'GHST_Death'
        GHST_Dharma = 'GHST_Dharma'
        GHST_IndustryGreen = 'GHST_IndustryGreen'
        GHST_IndustryMain = 'GHST_IndustryMain'
        GHST_IndustryOrange = 'GHST_IndustryOrange'
        GHST_IndustryRed = 'GHST_IndustryRed'
        GHST_Menu = 'GHST_Menu'
        GHST_Sensory = 'GHST_Sensory'
        GHST_Zipline = 'GHST_Zipline'
        SDKL_AlertEdgesOrange = 'SDKL_AlertEdgesOrange'
        SDKL_AlertEdgesYellow = 'SDKL_AlertEdgesYellow'
        SDKL_Melee = 'SDKL_Melee'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseBarWhite = 'SDKL_PulseBarWhite'
        SDKL_ScreenReactive = 'SDKL_ScreenReactive'
        SDKL_SplashBlue = 'SDKL_SplashBlue'
        SDKL_SplashGrey = 'SDKL_SplashGrey'
        SDKL_SplashYellow = 'SDKL_SplashYellow'


class GridForce(_Game):
    class Profile(_Profile):
        GRID_Dream = 'GRID_Dream'
        GRID_Menu = 'GRID_Menu'
        SDKL_EnvBlossom = 'SDKL_EnvBlossom'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkPink = 'SDKL_EnvDarkPink'
        SDKL_EnvGreen = 'SDKL_EnvGreen'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_Night = 'SDKL_Night'
        SDKL_PulseBarWhite = 'SDKL_PulseBarWhite'
        SDKL_PulsePink = 'SDKL_PulsePink'
        SDKL_PulseStarPink = 'SDKL_PulseStarPink'
        SDKL_SplashGrey = 'SDKL_SplashGrey'
        SDKL_SplashPink = 'SDKL_SplashPink'
        SDKL_TVNoise = 'SDKL_TVNoise'
        SDKL_Titanium = 'SDKL_Titanium'
        SDKL_UnderwaterBlue = 'SDKL_UnderwaterBlue'
        SDKL_WaveDownPink = 'SDKL_WaveDownPink'
        SDKL_WaveUpWhite = 'SDKL_WaveUpWhite'


class Hyperscape(_Game):
    class Profile(_Profile):
        HYPE_Assist = 'HYPE_Assist'
        HYPE_Break = 'HYPE_Break'
        HYPE_Card = 'HYPE_Card'
        HYPE_Crown = 'HYPE_Crown'
        HYPE_CrownAlmost = 'HYPE_CrownAlmost'
        HYPE_CrownStart = 'HYPE_CrownStart'
        HYPE_Damage = 'HYPE_Damage'
        HYPE_DamageEMP = 'HYPE_DamageEMP'
        HYPE_DamageMelee = 'HYPE_DamageMelee'
        HYPE_DamageShot = 'HYPE_DamageShot'
        HYPE_DamageZone = 'HYPE_DamageZone'
        HYPE_Day = 'HYPE_Day'
        HYPE_Death = 'HYPE_Death'
        HYPE_Default = 'HYPE_Default'
        HYPE_Emote = 'HYPE_Emote'
        HYPE_EmoteCorsair = 'HYPE_EmoteCorsair'
        HYPE_Fog = 'HYPE_Fog'
        HYPE_GameOver = 'HYPE_GameOver'
        HYPE_HackArmor = 'HYPE_HackArmor'
        HYPE_HackBall = 'HYPE_HackBall'
        HYPE_HackBallBounce = 'HYPE_HackBallBounce'
        HYPE_HackDefault = 'HYPE_HackDefault'
        HYPE_HackEMP = 'HYPE_HackEMP'
        HYPE_HackFirewall = 'HYPE_HackFirewall'
        HYPE_HackHeal = 'HYPE_HackHeal'
        HYPE_HackInvisibility = 'HYPE_HackInvisibility'
        HYPE_HackMagnet = 'HYPE_HackMagnet'
        HYPE_HackMine = 'HYPE_HackMine'
        HYPE_HackPickup = 'HYPE_HackPickup'
        HYPE_HackPowerRay = 'HYPE_HackPowerRay'
        HYPE_HackReveal = 'HYPE_HackReveal'
        HYPE_HackShockwave = 'HYPE_HackShockwave'
        HYPE_HackSlam = 'HYPE_HackSlam'
        HYPE_HackSlamHit = 'HYPE_HackSlamHit'
        HYPE_HackTeleport = 'HYPE_HackTeleport'
        HYPE_HackWall = 'HYPE_HackWall'
        HYPE_Healing = 'HYPE_Healing'
        HYPE_Hyperscape = 'HYPE_Hyperscape'
        HYPE_Insert = 'HYPE_Insert'
        HYPE_InsertFast = 'HYPE_InsertFast'
        HYPE_JumpPad = 'HYPE_JumpPad'
        HYPE_Kill = 'HYPE_Kill'
        HYPE_Loading = 'HYPE_Loading'
        HYPE_Lobby = 'HYPE_Lobby'
        HYPE_Map = 'HYPE_Map'
        HYPE_Morning = 'HYPE_Morning'
        HYPE_Night = 'HYPE_Night'
        HYPE_Pipe = 'HYPE_Pipe'
        HYPE_Revealed = 'HYPE_Revealed'
        HYPE_Revive = 'HYPE_Revive'
        HYPE_Reviving = 'HYPE_Reviving'
        HYPE_Spirit = 'HYPE_Spirit'
        HYPE_SquadAid = 'HYPE_SquadAid'
        HYPE_SquadDeath = 'HYPE_SquadDeath'
        HYPE_StaticHighlight1 = 'HYPE_StaticHighlight1'
        HYPE_StaticHighlight2 = 'HYPE_StaticHighlight2'
        HYPE_Sunrise = 'HYPE_Sunrise'
        HYPE_Sunset = 'HYPE_Sunset'
        HYPE_Tower = 'HYPE_Tower'
        HYPE_Victory = 'HYPE_Victory'
        HYPE_VictoryCrown = 'HYPE_VictoryCrown'
        HYPE_WeaponFusion = 'HYPE_WeaponFusion'
        HYPE_WeaponMFusion = 'HYPE_WeaponMFusion'
        HYPE_WeaponMelee = 'HYPE_WeaponMelee'
        HYPE_WeaponPickup = 'HYPE_WeaponPickup'
        HYPE_WeaponShoot = 'HYPE_WeaponShoot'
        HYPE_ZoneClosing = 'HYPE_ZoneClosing'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_Rain = 'SDKL_Rain'
        SDKL_StaticWhite = 'SDKL_StaticWhite'


class INMOST(_Game):
    class Profile(_Profile):
        INMO_Menu = 'INMO_Menu'
        SDKL_DamageCenter = 'SDKL_DamageCenter'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvSunset = 'SDKL_EnvSunset'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_PulseBarWhite = 'SDKL_PulseBarWhite'
        SDKL_PulseStarGrey = 'SDKL_PulseStarGrey'
        SDKL_WipeWhite = 'SDKL_WipeWhite'


class IXION(_Game):
    class Profile(_Profile):
        IXIO_Construction = 'IXIO_Construction'
        IXIO_EKP = 'IXIO_EKP'
        IXIO_Exterior = 'IXIO_Exterior'
        IXIO_GameOver = 'IXIO_GameOver'
        IXIO_Interior = 'IXIO_Interior'
        IXIO_Loading = 'IXIO_Loading'
        IXIO_MenuMain = 'IXIO_MenuMain'
        IXIO_Overload = 'IXIO_Overload'
        IXIO_Space = 'IXIO_Space'
        IXIO_Vohle = 'IXIO_Vohle'
        SDKL_AudioGold = 'SDKL_AudioGold'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_GlowOrange = 'SDKL_GlowOrange'
        SDKL_GlowRed = 'SDKL_GlowRed'
        SDKL_LightningStrike = 'SDKL_LightningStrike'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseGreen = 'SDKL_PulseGreen'
        SDKL_PulseYellow = 'SDKL_PulseYellow'
        SDKL_ShockRed = 'SDKL_ShockRed'
        SDKL_Snow = 'SDKL_Snow'
        SDKL_StaticBlack = 'SDKL_StaticBlack'
        SDKL_StaticEdgeGold = 'SDKL_StaticEdgeGold'
        SDKL_TVNoise = 'SDKL_TVNoise'
        SDKL_Titanium = 'SDKL_Titanium'
        SDKL_WaveUpWhite = 'SDKL_WaveUpWhite'


class MetroExodus(_Game):
    class Profile(_Profile):
        METE_Autumn = 'METE_Autumn'
        METE_BloodSplatter = 'METE_BloodSplatter'
        METE_Charger = 'METE_Charger'
        METE_DeadCity = 'METE_DeadCity'
        METE_DeathExplosion = 'METE_DeathExplosion'
        METE_DeathFire = 'METE_DeathFire'
        METE_DeathGas = 'METE_DeathGas'
        METE_DeathWater = 'METE_DeathWater'
        METE_DeathWound = 'METE_DeathWound'
        METE_Desert = 'METE_Desert'
        METE_Drinks = 'METE_Drinks'
        METE_Furnace = 'METE_Furnace'
        METE_Gas = 'METE_Gas'
        METE_Guitar = 'METE_Guitar'
        METE_Heart = 'METE_Heart'
        METE_Interior = 'METE_Interior'
        METE_Invisible = 'METE_Invisible'
        METE_KarmaBad = 'METE_KarmaBad'
        METE_KeyHint = 'METE_KeyHint'
        METE_Knockout = 'METE_Knockout'
        METE_LightOff = 'METE_LightOff'
        METE_LightOn = 'METE_LightOn'
        METE_Lighter = 'METE_Lighter'
        METE_Menu = 'METE_Menu'
        METE_Mushroom = 'METE_Mushroom'
        METE_Sandstorm = 'METE_Sandstorm'
        METE_Sleep = 'METE_Sleep'
        METE_Smoke = 'METE_Smoke'
        METE_SplashAqua = 'METE_SplashAqua'
        METE_SplashSpider = 'METE_SplashSpider'
        METE_Suffocate = 'METE_Suffocate'
        METE_Summer = 'METE_Summer'
        METE_Takedown = 'METE_Takedown'
        METE_Taxi = 'METE_Taxi'
        METE_WebBurn = 'METE_WebBurn'
        METE_Winter = 'METE_Winter'
        METE_Workbench = 'METE_Workbench'
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_FireHit = 'SDKL_FireHit'
        SDKL_FlashRed = 'SDKL_FlashRed'
        SDKL_FlashWhite = 'SDKL_FlashWhite'
        SDKL_Healing = 'SDKL_Healing'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_Lightning = 'SDKL_Lightning'
        SDKL_Melee = 'SDKL_Melee'
        SDKL_Qte = 'SDKL_Qte'
        SDKL_Radioactive = 'SDKL_Radioactive'
        SDKL_Rain = 'SDKL_Rain'
        SDKL_RangeHit = 'SDKL_RangeHit'
        SDKL_ShockBlue = 'SDKL_ShockBlue'
        SDKL_Snow = 'SDKL_Snow'
        SDKL_Underwater = 'SDKL_Underwater'
        SDKL_Water = 'SDKL_Water'


class MidnightGhostHunt(_Game):
    class Profile(_Profile):
        MNGH_Menu = 'MNGH_Menu'
        MNGH_Midnight = 'MNGH_Midnight'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_LootBlue = 'SDKL_LootBlue'
        SDKL_LootRed = 'SDKL_LootRed'
        SDKL_Night = 'SDKL_Night'
        SDKL_SmokeBlackout = 'SDKL_SmokeBlackout'


class OldWorld(_Game):
    class Profile(_Profile):
        OLDW_MenuMain = 'OLDW_MenuMain'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_FireHitRed = 'SDKL_FireHitRed'
        SDKL_LootYellow = 'SDKL_LootYellow'
        SDKL_PulseBarWhite = 'SDKL_PulseBarWhite'
        SDKL_SplashWhite = 'SDKL_SplashWhite'
        SDKL_StaticEdgeBlue = 'SDKL_StaticEdgeBlue'
        SDKL_StaticEdgeGold = 'SDKL_StaticEdgeGold'
        SDKL_StaticEdgeGreen = 'SDKL_StaticEdgeGreen'
        SDKL_StaticEdgeGrey = 'SDKL_StaticEdgeGrey'
        SDKL_StaticEdgeOrange = 'SDKL_StaticEdgeOrange'
        SDKL_StaticEdgePink = 'SDKL_StaticEdgePink'
        SDKL_StaticEdgePurple = 'SDKL_StaticEdgePurple'
        SDKL_StaticEdgeRed = 'SDKL_StaticEdgeRed'
        SDKL_StaticEdgeWhite = 'SDKL_StaticEdgeWhite'
        SDKL_StaticEdgeYellow = 'SDKL_StaticEdgeYellow'
        SDKL_WaveDownRed = 'SDKL_WaveDownRed'
        SDKL_WaveUpBlue = 'SDKL_WaveUpBlue'
        SDKL_WaveUpYellow = 'SDKL_WaveUpYellow'


class Overloop(_Game):
    class Profile(_Profile):
        OVLP_BossArena = 'OVLP_BossArena'
        OVLP_Menu = 'OVLP_Menu'
        OVLP_Reactor = 'OVLP_Reactor'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_Day = 'SDKL_Day'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvSunset = 'SDKL_EnvSunset'
        SDKL_EnvWhite = 'SDKL_EnvWhite'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_FadeToWhite = 'SDKL_FadeToWhite'
        SDKL_FlashBlue = 'SDKL_FlashBlue'
        SDKL_FlyingDown = 'SDKL_FlyingDown'
        SDKL_LootBlue = 'SDKL_LootBlue'
        SDKL_Night = 'SDKL_Night'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseBarGreen = 'SDKL_PulseBarGreen'
        SDKL_PulseBarYellow = 'SDKL_PulseBarYellow'
        SDKL_PulseGrey = 'SDKL_PulseGrey'
        SDKL_PulseStarBlue = 'SDKL_PulseStarBlue'
        SDKL_PulseStarYellow = 'SDKL_PulseStarYellow'
        SDKL_SplashBlue = 'SDKL_SplashBlue'
        SDKL_StaticBlack = 'SDKL_StaticBlack'
        SDKL_UnderwaterBlue = 'SDKL_UnderwaterBlue'
        SDKL_WaveDownWhite = 'SDKL_WaveDownWhite'


class PHOGS(_Game):
    _name = 'PHOGS!'

    class Profile(_Profile):
        PHOG_Food = 'PHOG_Food'
        PHOG_Play = 'PHOG_Play'
        PHOG_Tutorial = 'PHOG_Tutorial'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_AlertEdgesWhite = 'SDKL_AlertEdgesWhite'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_FireHitYellow = 'SDKL_FireHitYellow'
        SDKL_FirePink = 'SDKL_FirePink'
        SDKL_FireRed = 'SDKL_FireRed'
        SDKL_FireWhite = 'SDKL_FireWhite'
        SDKL_FlashWhite = 'SDKL_FlashWhite'
        SDKL_FlyingUp = 'SDKL_FlyingUp'
        SDKL_Ice = 'SDKL_Ice'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_PulseOrange = 'SDKL_PulseOrange'
        SDKL_PulseStarGrey = 'SDKL_PulseStarGrey'
        SDKL_ShapeSpinWhite = 'SDKL_ShapeSpinWhite'
        SDKL_SparksWhite = 'SDKL_SparksWhite'
        SDKL_SplashYellow = 'SDKL_SplashYellow'
        SDKL_Suffocate = 'SDKL_Suffocate'
        SDKL_WaterBlue = 'SDKL_WaterBlue'
        SDKL_WaterBrown = 'SDKL_WaterBrown'
        SDKL_WipeWhite = 'SDKL_WipeWhite'


class PlagueTaleRequiem(_Game):
    class Profile(_Profile):
        APTR_Menu = 'APTR_Menu'
        APTR_Rats = 'APTR_Rats'
        APTR_Sense = 'APTR_Sense'
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvShallows = 'SDKL_EnvShallows'
        SDKL_EnvSickly = 'SDKL_EnvSickly'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvVillage = 'SDKL_EnvVillage'
        SDKL_Sunset = 'SDKL_Sunset'
        SDKL_Titanium = 'SDKL_Titanium'


class ProjectWinter(_Game):
    class Profile(_Profile):
        PWIN_Ghost = 'PWIN_Ghost'
        PWIN_Menu = 'PWIN_Menu'
        PWIN_Neutral = 'PWIN_Neutral'
        PWIN_Survivor = 'PWIN_Survivor'
        PWIN_Traitor = 'PWIN_Traitor'
        SDKL_DamageClaws = 'SDKL_DamageClaws'
        SDKL_Drunk = 'SDKL_Drunk'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvWhite = 'SDKL_EnvWhite'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_FadeToWhite = 'SDKL_FadeToWhite'
        SDKL_Ice = 'SDKL_Ice'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_Lighter = 'SDKL_Lighter'
        SDKL_LootRed = 'SDKL_LootRed'
        SDKL_LootYellow = 'SDKL_LootYellow'
        SDKL_Neon = 'SDKL_Neon'
        SDKL_Night = 'SDKL_Night'
        SDKL_PulseBarYellow = 'SDKL_PulseBarYellow'
        SDKL_PulseCyan = 'SDKL_PulseCyan'
        SDKL_PulseGreen = 'SDKL_PulseGreen'
        SDKL_PulseOrange = 'SDKL_PulseOrange'
        SDKL_PulsePurple = 'SDKL_PulsePurple'
        SDKL_PulseStarBlack = 'SDKL_PulseStarBlack'
        SDKL_PulseStarOrange = 'SDKL_PulseStarOrange'
        SDKL_PulseYellow = 'SDKL_PulseYellow'
        SDKL_SplashRed = 'SDKL_SplashRed'
        SDKL_StaticBlack = 'SDKL_StaticBlack'


class RedSolstice2(_Game):
    class Profile(_Profile):
        RSL2_Menu = 'RSL2_Menu'
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_LootBlue = 'SDKL_LootBlue'
        SDKL_MushroomCloud = 'SDKL_MushroomCloud'
        SDKL_Night = 'SDKL_Night'
        SDKL_PulseBarRed = 'SDKL_PulseBarRed'
        SDKL_PulseBarYellow = 'SDKL_PulseBarYellow'
        SDKL_Smoke = 'SDKL_Smoke'
        SDKL_WaveDownPurple = 'SDKL_WaveDownPurple'


class SerialCleaners(_Game):
    class Profile(_Profile):
        SDKL_EnvAlpine = 'SDKL_EnvAlpine'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkOrange = 'SDKL_EnvDarkOrange'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_EnvDarkYellow = 'SDKL_EnvDarkYellow'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_FlashBlack = 'SDKL_FlashBlack'
        SDKL_PoliceLightsTop = 'SDKL_PoliceLightsTop'
        SDKL_PulseBarGreen = 'SDKL_PulseBarGreen'
        SDKL_PulseBlue = 'SDKL_PulseBlue'
        SDKL_Rain = 'SDKL_Rain'
        SDKL_SplashWhite = 'SDKL_SplashWhite'
        SDKL_SplashYellow = 'SDKL_SplashYellow'
        SDKL_Sunset = 'SDKL_Sunset'
        SECL_Arcade = 'SECL_Arcade'


class SeveredSteel(_Game):
    class Profile(_Profile):
        SDKL_Cobalt = 'SDKL_Cobalt'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvTech = 'SDKL_EnvTech'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_Nuclear = 'SDKL_Nuclear'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_PulsePink = 'SDKL_PulsePink'
        SDKL_SpeedLines = 'SDKL_SpeedLines'
        SDKL_Titanium = 'SDKL_Titanium'
        SDKL_WaterBlue = 'SDKL_WaterBlue'
        SDKL_WaterCyan = 'SDKL_WaterCyan'


class ShipOfFools(_Game):
    class Profile(_Profile):
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_GlowRed = 'SDKL_GlowRed'
        SDKL_Lava = 'SDKL_Lava'
        SDKL_LightningStrike = 'SDKL_LightningStrike'
        SDKL_PulseStarWhite = 'SDKL_PulseStarWhite'
        SDKL_WaterBlue = 'SDKL_WaterBlue'
        SDKL_WaterCyan = 'SDKL_WaterCyan'
        SHIP_Boss = 'SHIP_Boss'
        SHIP_Edge = 'SHIP_Edge'
        SHIP_Menu = 'SHIP_Menu'


class SIFU(_Game):
    class Profile(_Profile):
        SDKL_Brimstone = 'SDKL_Brimstone'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_FadeToWhite = 'SDKL_FadeToWhite'
        SDKL_PulseBarWhite = 'SDKL_PulseBarWhite'
        SDKL_SmokeBlackout = 'SDKL_SmokeBlackout'
        SDKL_SplashBlue = 'SDKL_SplashBlue'
        SDKL_SplashGreen = 'SDKL_SplashGreen'
        SDKL_SplashRed = 'SDKL_SplashRed'
        SDKL_SplashTan = 'SDKL_SplashTan'
        SDKL_SplashWhite = 'SDKL_SplashWhite'
        SDKL_SplashYellow = 'SDKL_SplashYellow'
        SDKL_StaticWhite = 'SDKL_StaticWhite'
        SDKL_Titanium = 'SDKL_Titanium'
        SIFU_Squats = 'SIFU_Squats'
        SIFU_Tower = 'SIFU_Tower'
        SIFU_Wuguan = 'SIFU_Wuguan'


class Starmancer(_Game):
    class Profile(_Profile):
        SDKL_Brimstone = 'SDKL_Brimstone'
        SDKL_Cobalt = 'SDKL_Cobalt'
        SDKL_Crimson = 'SDKL_Crimson'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_FireGreen = 'SDKL_FireGreen'
        SDKL_FireYellow = 'SDKL_FireYellow'
        SDKL_HintBlue = 'SDKL_HintBlue'
        SDKL_Nuclear = 'SDKL_Nuclear'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseStarBlue = 'SDKL_PulseStarBlue'
        SDKL_StaticBlack25 = 'SDKL_StaticBlack25'
        SDKL_StaticBlack50 = 'SDKL_StaticBlack50'
        SDKL_StaticBlack75 = 'SDKL_StaticBlack75'
        SDKL_WaveDownRed = 'SDKL_WaveDownRed'
        STAR_Menu = 'STAR_Menu'
        STAR_Purge = 'STAR_Purge'
        STAR_SpeedDouble = 'STAR_SpeedDouble'
        STAR_SpeedNormal = 'STAR_SpeedNormal'
        STAR_SpeedPaused = 'STAR_SpeedPaused'
        STAR_SpeedTriple = 'STAR_SpeedTriple'


class SubnauticaBZ(_Game):
    class Profile(_Profile):
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_AlertEdgesBlue = 'SDKL_AlertEdgesBlue'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_AlertEdgesYellow = 'SDKL_AlertEdgesYellow'
        SDKL_BloodSplatter = 'SDKL_BloodSplatter'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_FireLime = 'SDKL_FireLime'
        SDKL_Ice = 'SDKL_Ice'
        SDKL_Night = 'SDKL_Night'
        SDKL_NightDark = 'SDKL_NightDark'
        SDKL_SparksWhite = 'SDKL_SparksWhite'
        SDKL_Underwater = 'SDKL_Underwater'
        SDKL_UnderwaterBlue = 'SDKL_UnderwaterBlue'
        SDKL_UnderwaterCyan = 'SDKL_UnderwaterCyan'
        SDKL_WaterBlue = 'SDKL_WaterBlue'
        SDKL_WaterBrown = 'SDKL_WaterBrown'
        SDKL_WaterCyan = 'SDKL_WaterCyan'


class SuperMagBot(_Game):
    class Profile(_Profile):
        MAGB_ChargeB1 = 'MAGB_ChargeB1'
        MAGB_ChargeB2 = 'MAGB_ChargeB2'
        MAGB_ChargeR1 = 'MAGB_ChargeR1'
        MAGB_ChargeR2 = 'MAGB_ChargeR2'
        MAGB_Charges = 'MAGB_Charges'
        MAGB_DashBlue = 'MAGB_DashBlue'
        MAGB_DashRed = 'MAGB_DashRed'
        MAGB_Magnetia = 'MAGB_Magnetia'
        MAGB_Menu = 'MAGB_Menu'
        SDKL_Brimstone = 'SDKL_Brimstone'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_Ice = 'SDKL_Ice'
        SDKL_Neon = 'SDKL_Neon'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseBarPink = 'SDKL_PulseBarPink'
        SDKL_PulseBarRed = 'SDKL_PulseBarRed'
        SDKL_PulseBarYellow = 'SDKL_PulseBarYellow'
        SDKL_PulseStarCyan = 'SDKL_PulseStarCyan'
        SDKL_PulseStarGreen = 'SDKL_PulseStarGreen'
        SDKL_PulseStarOrange = 'SDKL_PulseStarOrange'
        SDKL_PulseStarPink = 'SDKL_PulseStarPink'
        SDKL_PulseStarYellow = 'SDKL_PulseStarYellow'
        SDKL_PulseYellow = 'SDKL_PulseYellow'


class SweetTransit(_Game):
    class Profile(_Profile):
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvWhite = 'SDKL_EnvWhite'
        SDKL_SplashBlue = 'SDKL_SplashBlue'
        SDKL_UnderwaterBlue = 'SDKL_UnderwaterBlue'
        SWTN_Menu = 'SWTN_Menu'
        SWTN_Town = 'SWTN_Town'
        SWTN_Trains = 'SWTN_Trains'
        SWTN_Village = 'SWTN_Village'


class TerraInvicta(_Game):
    class Profile(_Profile):
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_MushroomCloud = 'SDKL_MushroomCloud'
        SDKL_PulseBarGreen = 'SDKL_PulseBarGreen'
        SDKL_PulseBarRed = 'SDKL_PulseBarRed'
        SDKL_Zoom = 'SDKL_Zoom'
        TRIN_Earth = 'TRIN_Earth'
        TRIN_EncounterAliens = 'TRIN_EncounterAliens'
        TRIN_EncounterBlue = 'TRIN_EncounterBlue'
        TRIN_EncounterCyan = 'TRIN_EncounterCyan'
        TRIN_EncounterGreen = 'TRIN_EncounterGreen'
        TRIN_EncounterOrange = 'TRIN_EncounterOrange'
        TRIN_EncounterPurple = 'TRIN_EncounterPurple'
        TRIN_EncounterRed = 'TRIN_EncounterRed'
        TRIN_EncounterYellow = 'TRIN_EncounterYellow'
        TRIN_FactionBlue = 'TRIN_FactionBlue'
        TRIN_FactionCyan = 'TRIN_FactionCyan'
        TRIN_FactionGreen = 'TRIN_FactionGreen'
        TRIN_FactionOrange = 'TRIN_FactionOrange'
        TRIN_FactionPurple = 'TRIN_FactionPurple'
        TRIN_FactionRed = 'TRIN_FactionRed'
        TRIN_FactionYellow = 'TRIN_FactionYellow'
        TRIN_Menu = 'TRIN_Menu'
        TRIN_Space = 'TRIN_Space'


class TheDivision2(_Game):
    class Profile(_Profile):
        DIV2_Bleed = 'DIV2_Bleed'
        DIV2_Blind = 'DIV2_Blind'
        DIV2_Confuse = 'DIV2_Confuse'
        DIV2_Day = 'DIV2_Day'
        DIV2_Death = 'DIV2_Death'
        DIV2_DeathBleed = 'DIV2_DeathBleed'
        DIV2_DeathFire = 'DIV2_DeathFire'
        DIV2_DeathPoison = 'DIV2_DeathPoison'
        DIV2_Default = 'DIV2_Default'
        DIV2_Disrupt = 'DIV2_Disrupt'
        DIV2_Downed = 'DIV2_Downed'
        DIV2_EnemyDetected = 'DIV2_EnemyDetected'
        DIV2_EnemyScanned = 'DIV2_EnemyScanned'
        DIV2_Ensnare = 'DIV2_Ensnare'
        DIV2_Flare = 'DIV2_Flare'
        DIV2_Hint = 'DIV2_Hint'
        DIV2_Keeners = 'DIV2_Keeners'
        DIV2_LevelUp = 'DIV2_LevelUp'
        DIV2_LevelUpSeasons = 'DIV2_LevelUpSeasons'
        DIV2_Loot = 'DIV2_Loot'
        DIV2_Map = 'DIV2_Map'
        DIV2_Memory = 'DIV2_Memory'
        DIV2_Menu = 'DIV2_Menu'
        DIV2_Night = 'DIV2_Night'
        DIV2_Poison = 'DIV2_Poison'
        DIV2_Pulse = 'DIV2_Pulse'
        DIV2_PulseJam = 'DIV2_PulseJam'
        DIV2_PulseScan = 'DIV2_PulseScan'
        DIV2_RogueAgents = 'DIV2_RogueAgents'
        DIV2_SafeZone = 'DIV2_SafeZone'
        DIV2_Salvage = 'DIV2_Salvage'
        DIV2_Shock = 'DIV2_Shock'
        DIV2_Stealth = 'DIV2_Stealth'
        DIV2_Victory = 'DIV2_Victory'
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_Explosion = 'SDKL_Explosion'
        SDKL_Fire = 'SDKL_Fire'
        SDKL_FireHit = 'SDKL_FireHit'
        SDKL_Fog = 'SDKL_Fog'
        SDKL_Healing = 'SDKL_Healing'
        SDKL_Melee = 'SDKL_Melee'
        SDKL_Rain = 'SDKL_Rain'
        SDKL_RangeHit = 'SDKL_RangeHit'


class TheMedium(_Game):
    class Profile(_Profile):
        MEDI_EnvDarkGreen_H = 'MEDI_EnvDarkGreen_H'
        MEDI_EnvDarkGreen_V = 'MEDI_EnvDarkGreen_V'
        MEDI_EnvDark_H = 'MEDI_EnvDark_H'
        MEDI_EnvDark_V = 'MEDI_EnvDark_V'
        SDKL_Death = 'SDKL_Death'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_FlashGrey = 'SDKL_FlashGrey'
        SDKL_FlashWhite = 'SDKL_FlashWhite'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_LightningStrike = 'SDKL_LightningStrike'
        SDKL_LootWhite = 'SDKL_LootWhite'
        SDKL_PulseGrey = 'SDKL_PulseGrey'
        SDKL_ShapeSpinWhite = 'SDKL_ShapeSpinWhite'
        SDKL_SplashOrange = 'SDKL_SplashOrange'
        SDKL_StaticBlack = 'SDKL_StaticBlack'


class Thymesia(_Game):
    class Profile(_Profile):
        SDKL_Cutscene = 'SDKL_Cutscene'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_FadeToBlack = 'SDKL_FadeToBlack'
        SDKL_PulseWhite = 'SDKL_PulseWhite'
        SDKL_SmokeBlackout = 'SDKL_SmokeBlackout'
        SDKL_SparksRed = 'SDKL_SparksRed'
        SDKL_SplashWhite = 'SDKL_SplashWhite'
        THYM_FlashTeal = 'THYM_FlashTeal'
        THYM_Fortress = 'THYM_Fortress'
        THYM_MenuPause = 'THYM_MenuPause'
        THYM_PulseBarTeal = 'THYM_PulseBarTeal'
        THYM_RoyalGarden = 'THYM_RoyalGarden'
        THYM_SeaOfTrees = 'THYM_SeaOfTrees'
        THYM_WaveDownTeal = 'THYM_WaveDownTeal'


class TribesOfMidgard(_Game):
    class Profile(_Profile):
        SDKL_Alarm = 'SDKL_Alarm'
        SDKL_AlertEdgesRed = 'SDKL_AlertEdgesRed'
        SDKL_Bleeding = 'SDKL_Bleeding'
        SDKL_Cobalt = 'SDKL_Cobalt'
        SDKL_DamageCenter = 'SDKL_DamageCenter'
        SDKL_EnvAutumn = 'SDKL_EnvAutumn'
        SDKL_EnvDark = 'SDKL_EnvDark'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_FadeToGrey = 'SDKL_FadeToGrey'
        SDKL_FireHitYellow = 'SDKL_FireHitYellow'
        SDKL_LootGreen = 'SDKL_LootGreen'
        SDKL_LootOrange = 'SDKL_LootOrange'
        SDKL_LootRed = 'SDKL_LootRed'
        SDKL_LootYellow = 'SDKL_LootYellow'
        SDKL_PulseBarBlue = 'SDKL_PulseBarBlue'
        SDKL_PulseBarGreen = 'SDKL_PulseBarGreen'
        SDKL_PulseBarGrey = 'SDKL_PulseBarGrey'
        SDKL_PulseBarRed = 'SDKL_PulseBarRed'
        SDKL_PulseBarYellow = 'SDKL_PulseBarYellow'
        SDKL_PulseBlue = 'SDKL_PulseBlue'
        SDKL_PulseGreen = 'SDKL_PulseGreen'
        SDKL_PulseGrey = 'SDKL_PulseGrey'
        SDKL_PulsePurple = 'SDKL_PulsePurple'
        SDKL_PulseStarWhite = 'SDKL_PulseStarWhite'
        SDKL_PulseStarYellow = 'SDKL_PulseStarYellow'
        SDKL_PulseYellow = 'SDKL_PulseYellow'
        SDKL_SplashWhite = 'SDKL_SplashWhite'
        SDKL_StaticBlack = 'SDKL_StaticBlack'
        SDKL_StaticGrey = 'SDKL_StaticGrey'
        SDKL_StaticOrange25 = 'SDKL_StaticOrange25'
        SDKL_StaticOrgange25 = 'SDKL_StaticOrgange25'
        SDKL_StaticPurple50 = 'SDKL_StaticPurple50'
        SDKL_UnderwaterCyan = 'SDKL_UnderwaterCyan'
        SDKL_WaveUpRed = 'SDKL_WaveUpRed'
        TOMG_Menu = 'TOMG_Menu'


class Vesper(_Game):
    class Profile(_Profile):
        SDKL_Brimstone = 'SDKL_Brimstone'
        SDKL_Cobalt = 'SDKL_Cobalt'
        SDKL_Corrosive = 'SDKL_Corrosive'
        SDKL_Crimson = 'SDKL_Crimson'
        SDKL_EnvDarkBlue = 'SDKL_EnvDarkBlue'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvDarkRed = 'SDKL_EnvDarkRed'
        SDKL_FirePurple = 'SDKL_FirePurple'
        SDKL_Neon = 'SDKL_Neon'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_ShockBlue = 'SDKL_ShockBlue'
        SDKL_Smoke = 'SDKL_Smoke'
        SDKL_SparksWhite = 'SDKL_SparksWhite'
        SDKL_StaticWhite = 'SDKL_StaticWhite'
        SDKL_Sunset = 'SDKL_Sunset'
        SDKL_TVNoise = 'SDKL_TVNoise'
        SDKL_UnderwaterBlue = 'SDKL_UnderwaterBlue'
        SDKL_UnderwaterCyan = 'SDKL_UnderwaterCyan'
        SDKL_WaveDownPurple = 'SDKL_WaveDownPurple'


class Wonderlands(_Game):
    class Profile(_Profile):
        SDKL_EnvAlpine = 'SDKL_EnvAlpine'
        SDKL_EnvDarkGreen = 'SDKL_EnvDarkGreen'
        SDKL_EnvDarkGrey = 'SDKL_EnvDarkGrey'
        SDKL_EnvMud = 'SDKL_EnvMud'
        SDKL_EnvSand = 'SDKL_EnvSand'
        SDKL_EnvSummer = 'SDKL_EnvSummer'
        SDKL_EnvWinter = 'SDKL_EnvWinter'
        SDKL_Injured = 'SDKL_Injured'
        SDKL_LootPurple = 'SDKL_LootPurple'
        SDKL_LootWhite = 'SDKL_LootWhite'
        SDKL_Poison = 'SDKL_Poison'
        SDKL_PulseBarPurple = 'SDKL_PulseBarPurple'
        SDKL_PulseBarTan = 'SDKL_PulseBarTan'
        SDKL_PulseGrey = 'SDKL_PulseGrey'
        SDKL_PulseStarTan = 'SDKL_PulseStarTan'
        SDKL_PulseTan = 'SDKL_PulseTan'
        SDKL_SparksBlue = 'SDKL_SparksBlue'
        SDKL_SparksGreen = 'SDKL_SparksGreen'
        SDKL_SplashPurple = 'SDKL_SplashPurple'
        SDKL_SplashWhite = 'SDKL_SplashWhite'
        SDKL_Titanium = 'SDKL_Titanium'
        SDKL_WaveDownWhite = 'SDKL_WaveDownWhite'
        SDKL_WaveUpWhite = 'SDKL_WaveUpWhite'
        SDKL_WhirlwindPurple = 'SDKL_WhirlwindPurple'
        SDKL_WhirlwindWhite = 'SDKL_WhirlwindWhite'
        TTWL_Abyss = 'TTWL_Abyss'
        TTWL_Beanstalk = 'TTWL_Beanstalk'
        TTWL_BrrZerkerRage = 'TTWL_BrrZerkerRage'
        TTWL_CleansingFlames = 'TTWL_CleansingFlames'
        TTWL_Climb = 'TTWL_Climb'
        TTWL_DireSacrifice = 'TTWL_DireSacrifice'
        TTWL_DungeonDesert = 'TTWL_DungeonDesert'
        TTWL_EtherealBow = 'TTWL_EtherealBow'
        TTWL_FFYL = 'TTWL_FFYL'
        TTWL_Grasslands = 'TTWL_Grasslands'
        TTWL_Hubtown = 'TTWL_Hubtown'
        TTWL_LegendarySpawn = 'TTWL_LegendarySpawn'
        TTWL_LevelUp = 'TTWL_LevelUp'
        TTWL_Loading = 'TTWL_Loading'
        TTWL_MenuMain = 'TTWL_MenuMain'
        TTWL_Mushroom = 'TTWL_Mushroom'
        TTWL_Oasis = 'TTWL_Oasis'
        TTWL_Overworld = 'TTWL_Overworld'
        TTWL_PolymorphStart = 'TTWL_PolymorphStart'
        TTWL_QuickChange = 'TTWL_QuickChange'
        TTWL_Reaper = 'TTWL_Reaper'
        TTWL_Resurrect = 'TTWL_Resurrect'
        TTWL_Seabed = 'TTWL_Seabed'
        TTWL_ShadowsActive = 'TTWL_ShadowsActive'


os.add_dll_directory(ntpath.join(ntpath.dirname(__file__)))
