on: push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: .\build.ps1 Install-Dependencies
      - name: Build repository
        run: .\build.ps1
      - name: Upload build
        env:
          MEGA_USERNAME: ${{ secrets.USERNAME }}
          MEGA_PASSWORD: ${{ secrets.PASSWORD }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: .\build.ps1 Upload-Build