on: push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    steps:
      - name: Configure command prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: .\build.ps1 install
      - name: Build project
        run: .\build.ps1
      - name: Upload build
        #        env:
        #          MEGA_USERNAME: ${{ secrets.MEGA_USERNAME }}
        #          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}
        #          PYTHON_VERSION: ${{ matrix.python-version }}
        #        run: .\build.ps1 upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: dist/*