name: Produce nightly build
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  check:
    name: Check latest commit
    runs-on: windows-latest
    outputs:
      committed: ${{ steps.committed.outputs.committed }}
    steps:
      - name: Check if committed last day
        id: 'committed'
        run: echo "::set-output name=committed::$( (Invoke-WebRequest https://api.github.com/repos/$Env:GITHUB_REPOSITORY/commits -Headers @{ Authorization = "token ${{ secrets.GITHUB_TOKEN }}" } -Body @{ since = Get-Date (Get-Date).AddDays(-1) -Format "yyyy/MM/ddTHH:mm:ssZ" }).RawContentLength -ne 2 )"
  build:
    name: Continue with build
    needs: check
    if: needs.check.outputs.committed == 'True'
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: .\build.ps1 Install-Dependecies
      - name: Build repository
        run: .\build.ps1
      - name: Upload ${{ env.NAME }}.zip
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.NAME }}
          path: dist/*
          if-no-files-found: error